package positionwebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "positionService", targetNamespace = "positionWebService")
public interface PositionService {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "queryPositionInfoChangeFromHRToOA", targetNamespace = "positionWebService", className = "positionwebservice.QueryPositionInfoChangeFromHRToOA")
	@ResponseWrapper(localName = "queryPositionInfoChangeFromHRToOAResponse", targetNamespace = "positionWebService", className = "positionwebservice.QueryPositionInfoChangeFromHRToOAResponse")
	public String queryPositionInfoChangeFromHRToOA(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
