package com.creditease.eas.admin.bean;

public class AdminUserPort {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_REL_USERPORT.FID
     *
     * @mbggenerated Fri May 30 11:07:18 CST 2014
     */
    private Long fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_REL_USERPORT.FUSERID
     *
     * @mbggenerated Fri May 30 11:07:18 CST 2014
     */
    private Long fuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_REL_USERPORT.PORTID
     *
     * @mbggenerated Fri May 30 11:07:18 CST 2014
     */
    private Long portid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_REL_USERPORT.FID
     *
     * @return the value of T_ADMIN_REL_USERPORT.FID
     *
     * @mbggenerated Fri May 30 11:07:18 CST 2014
     */
    public Long getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_REL_USERPORT.FID
     *
     * @param fid the value for T_ADMIN_REL_USERPORT.FID
     *
     * @mbggenerated Fri May 30 11:07:18 CST 2014
     */
    public void setFid(Long fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_REL_USERPORT.FUSERID
     *
     * @return the value of T_ADMIN_REL_USERPORT.FUSERID
     *
     * @mbggenerated Fri May 30 11:07:18 CST 2014
     */
    public Long getFuserid() {
        return fuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_REL_USERPORT.FUSERID
     *
     * @param fuserid the value for T_ADMIN_REL_USERPORT.FUSERID
     *
     * @mbggenerated Fri May 30 11:07:18 CST 2014
     */
    public void setFuserid(Long fuserid) {
        this.fuserid = fuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_REL_USERPORT.PORTID
     *
     * @return the value of T_ADMIN_REL_USERPORT.PORTID
     *
     * @mbggenerated Fri May 30 11:07:18 CST 2014
     */
    public Long getPortid() {
        return portid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_REL_USERPORT.PORTID
     *
     * @param portid the value for T_ADMIN_REL_USERPORT.PORTID
     *
     * @mbggenerated Fri May 30 11:07:18 CST 2014
     */
    public void setPortid(Long portid) {
        this.portid = portid;
    }
}