package com.creditease.eas.admin.bean;
/***
 * 接口人和用户中间表
 * @Title:AdminUserAuthority.java
 * @Package com.creditease.eas.admin.bean
 * created at 2014-5-26 上午11:06:09 by ygq
 * @author ygq
 * @version 1.0
 */
public class AdminUserAuthority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_REL_USERAUTHORITY.FID
     *
     * @mbggenerated Mon May 26 11:03:48 CST 2014
     */
    private Long fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_REL_USERAUTHORITY.FUSERID
     *
     * @mbggenerated Mon May 26 11:03:48 CST 2014
     */
    private Long fuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_REL_USERAUTHORITY.AUTHORITYID
     *
     * @mbggenerated Mon May 26 11:03:48 CST 2014
     */
    private Long authorityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_REL_USERAUTHORITY.FID
     *
     * @return the value of T_ADMIN_REL_USERAUTHORITY.FID
     *
     * @mbggenerated Mon May 26 11:03:48 CST 2014
     */
    public Long getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_REL_USERAUTHORITY.FID
     *
     * @param fid the value for T_ADMIN_REL_USERAUTHORITY.FID
     *
     * @mbggenerated Mon May 26 11:03:48 CST 2014
     */
    public void setFid(Long fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_REL_USERAUTHORITY.FUSERID
     *
     * @return the value of T_ADMIN_REL_USERAUTHORITY.FUSERID
     *
     * @mbggenerated Mon May 26 11:03:48 CST 2014
     */
    public Long getFuserid() {
        return fuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_REL_USERAUTHORITY.FUSERID
     *
     * @param fuserid the value for T_ADMIN_REL_USERAUTHORITY.FUSERID
     *
     * @mbggenerated Mon May 26 11:03:48 CST 2014
     */
    public void setFuserid(Long fuserid) {
        this.fuserid = fuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_REL_USERAUTHORITY.AUTHORITYID
     *
     * @return the value of T_ADMIN_REL_USERAUTHORITY.AUTHORITYID
     *
     * @mbggenerated Mon May 26 11:03:48 CST 2014
     */
    public Long getAuthorityid() {
        return authorityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_REL_USERAUTHORITY.AUTHORITYID
     *
     * @param authorityid the value for T_ADMIN_REL_USERAUTHORITY.AUTHORITYID
     *
     * @mbggenerated Mon May 26 11:03:48 CST 2014
     */
    public void setAuthorityid(Long authorityid) {
        this.authorityid = authorityid;
    }
}