package com.creditease.eas.admin.bean;

public class Function {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.id
     *
     * @mbggenerated Mon Aug 05 15:52:48 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.funname
     *
     * @mbggenerated Mon Aug 05 15:52:48 CST 2013
     */
    private String funname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.url
     *
     * @mbggenerated Mon Aug 05 15:52:48 CST 2013
     */
    private String url;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.stutas
     *
     * @mbggenerated Mon Aug 05 15:52:48 CST 2013
     */
    private Integer stutas;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.id
     *
     * @return the value of t_function.id
     *
     * @mbggenerated Mon Aug 05 15:52:48 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.id
     *
     * @param id the value for t_function.id
     *
     * @mbggenerated Mon Aug 05 15:52:48 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.funname
     *
     * @return the value of t_function.funname
     *
     * @mbggenerated Mon Aug 05 15:52:48 CST 2013
     */
    public String getFunname() {
        return funname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.funname
     *
     * @param funname the value for t_function.funname
     *
     * @mbggenerated Mon Aug 05 15:52:48 CST 2013
     */
    public void setFunname(String funname) {
        this.funname = funname == null ? null : funname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.url
     *
     * @return the value of t_function.url
     *
     * @mbggenerated Mon Aug 05 15:52:48 CST 2013
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.url
     *
     * @param url the value for t_function.url
     *
     * @mbggenerated Mon Aug 05 15:52:48 CST 2013
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.stutas
     *
     * @return the value of t_function.stutas
     *
     * @mbggenerated Mon Aug 05 15:52:48 CST 2013
     */
    public Integer getStutas() {
        return stutas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.stutas
     *
     * @param stutas the value for t_function.stutas
     *
     * @mbggenerated Mon Aug 05 15:52:48 CST 2013
     */
    public void setStutas(Integer stutas) {
        this.stutas = stutas;
    }
}