package com.creditease.eas.admin.bean;

public class RoleFunction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_function.id
     *
     * @mbggenerated Wed Aug 14 16:11:18 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_function.function_id
     *
     * @mbggenerated Wed Aug 14 16:11:18 CST 2013
     */
    private Integer functionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_function.role_id
     *
     * @mbggenerated Wed Aug 14 16:11:18 CST 2013
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_function.linktype
     *
     * @mbggenerated Wed Aug 14 16:11:18 CST 2013
     */
    private Integer linktype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_function.stutas
     *
     * @mbggenerated Wed Aug 14 16:11:18 CST 2013
     */
    private Integer stutas;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_function.id
     *
     * @return the value of t_role_function.id
     *
     * @mbggenerated Wed Aug 14 16:11:18 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_function.id
     *
     * @param id the value for t_role_function.id
     *
     * @mbggenerated Wed Aug 14 16:11:18 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_function.function_id
     *
     * @return the value of t_role_function.function_id
     *
     * @mbggenerated Wed Aug 14 16:11:18 CST 2013
     */
    public Integer getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_function.function_id
     *
     * @param functionId the value for t_role_function.function_id
     *
     * @mbggenerated Wed Aug 14 16:11:18 CST 2013
     */
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_function.role_id
     *
     * @return the value of t_role_function.role_id
     *
     * @mbggenerated Wed Aug 14 16:11:18 CST 2013
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_function.role_id
     *
     * @param roleId the value for t_role_function.role_id
     *
     * @mbggenerated Wed Aug 14 16:11:18 CST 2013
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_function.linktype
     *
     * @return the value of t_role_function.linktype
     *
     * @mbggenerated Wed Aug 14 16:11:18 CST 2013
     */
    public Integer getLinktype() {
        return linktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_function.linktype
     *
     * @param linktype the value for t_role_function.linktype
     *
     * @mbggenerated Wed Aug 14 16:11:18 CST 2013
     */
    public void setLinktype(Integer linktype) {
        this.linktype = linktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_function.stutas
     *
     * @return the value of t_role_function.stutas
     *
     * @mbggenerated Wed Aug 14 16:11:18 CST 2013
     */
    public Integer getStutas() {
        return stutas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_function.stutas
     *
     * @param stutas the value for t_role_function.stutas
     *
     * @mbggenerated Wed Aug 14 16:11:18 CST 2013
     */
    public void setStutas(Integer stutas) {
        this.stutas = stutas;
    }
}