package com.creditease.eas.admin.bean;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userrole.id
     *
     * @mbggenerated Tue Aug 06 23:10:32 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userrole.userid
     *
     * @mbggenerated Tue Aug 06 23:10:32 CST 2013
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userrole.roleid
     *
     * @mbggenerated Tue Aug 06 23:10:32 CST 2013
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userrole.stutas
     *
     * @mbggenerated Tue Aug 06 23:10:32 CST 2013
     */
    private Integer stutas;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userrole.id
     *
     * @return the value of t_userrole.id
     *
     * @mbggenerated Tue Aug 06 23:10:32 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userrole.id
     *
     * @param id the value for t_userrole.id
     *
     * @mbggenerated Tue Aug 06 23:10:32 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userrole.userid
     *
     * @return the value of t_userrole.userid
     *
     * @mbggenerated Tue Aug 06 23:10:32 CST 2013
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userrole.userid
     *
     * @param userid the value for t_userrole.userid
     *
     * @mbggenerated Tue Aug 06 23:10:32 CST 2013
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userrole.roleid
     *
     * @return the value of t_userrole.roleid
     *
     * @mbggenerated Tue Aug 06 23:10:32 CST 2013
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userrole.roleid
     *
     * @param roleid the value for t_userrole.roleid
     *
     * @mbggenerated Tue Aug 06 23:10:32 CST 2013
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userrole.stutas
     *
     * @return the value of t_userrole.stutas
     *
     * @mbggenerated Tue Aug 06 23:10:32 CST 2013
     */
    public Integer getStutas() {
        return stutas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userrole.stutas
     *
     * @param stutas the value for t_userrole.stutas
     *
     * @mbggenerated Tue Aug 06 23:10:32 CST 2013
     */
    public void setStutas(Integer stutas) {
        this.stutas = stutas;
    }
}