package com.creditease.eas.hr.bean;

import java.util.Date;

public class Wsorganization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.ID
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.FNUMBER
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private String fnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.PRINCIPALID
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private String principalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.FINDEX
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private Long findex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.PARENTNUMBER
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private String parentnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.FEFFECTDATE
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private Date feffectdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.FINVALIDDATE
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private Date finvaliddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.ISFREEZE
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private String isfreeze;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.FISSTART
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private String fisstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.FORGTYPESTR
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private String forgtypestr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.ISLEAF
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private String isleaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.FLEVEL
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private Integer flevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.DISPLAYNAME
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private String displayname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.DESCRIPTION
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.SIMPLENAME
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private String simplename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.RECDATE
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private Date recdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.T_LOG_BASEID
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private Long tLogBaseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.ISCOSTCENTER
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private String iscostcenter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_ORGANIZATION.PUSHTIME
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    private Date pushtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.ID
     *
     * @return the value of T_LOG_WS_ORGANIZATION.ID
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.ID
     *
     * @param id the value for T_LOG_WS_ORGANIZATION.ID
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.FNUMBER
     *
     * @return the value of T_LOG_WS_ORGANIZATION.FNUMBER
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public String getFnumber() {
        return fnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.FNUMBER
     *
     * @param fnumber the value for T_LOG_WS_ORGANIZATION.FNUMBER
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void setFnumber(String fnumber) {
        this.fnumber = fnumber == null ? null : fnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.PRINCIPALID
     *
     * @return the value of T_LOG_WS_ORGANIZATION.PRINCIPALID
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public String getPrincipalid() {
        return principalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.PRINCIPALID
     *
     * @param principalid the value for T_LOG_WS_ORGANIZATION.PRINCIPALID
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void setPrincipalid(String principalid) {
        this.principalid = principalid == null ? null : principalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.FINDEX
     *
     * @return the value of T_LOG_WS_ORGANIZATION.FINDEX
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public Long getFindex() {
        return findex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.FINDEX
     *
     * @param findex the value for T_LOG_WS_ORGANIZATION.FINDEX
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void setFindex(Long findex) {
        this.findex = findex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.PARENTNUMBER
     *
     * @return the value of T_LOG_WS_ORGANIZATION.PARENTNUMBER
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public String getParentnumber() {
        return parentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.PARENTNUMBER
     *
     * @param parentnumber the value for T_LOG_WS_ORGANIZATION.PARENTNUMBER
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void setParentnumber(String parentnumber) {
        this.parentnumber = parentnumber == null ? null : parentnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.FEFFECTDATE
     *
     * @return the value of T_LOG_WS_ORGANIZATION.FEFFECTDATE
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public Date getFeffectdate() {
        return feffectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.FEFFECTDATE
     *
     * @param feffectdate the value for T_LOG_WS_ORGANIZATION.FEFFECTDATE
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void setFeffectdate(Date feffectdate) {
        this.feffectdate = feffectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.FINVALIDDATE
     *
     * @return the value of T_LOG_WS_ORGANIZATION.FINVALIDDATE
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public Date getFinvaliddate() {
        return finvaliddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.FINVALIDDATE
     *
     * @param finvaliddate the value for T_LOG_WS_ORGANIZATION.FINVALIDDATE
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void setFinvaliddate(Date finvaliddate) {
        this.finvaliddate = finvaliddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.ISFREEZE
     *
     * @return the value of T_LOG_WS_ORGANIZATION.ISFREEZE
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public String getIsfreeze() {
        return isfreeze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.ISFREEZE
     *
     * @param isfreeze the value for T_LOG_WS_ORGANIZATION.ISFREEZE
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void setIsfreeze(String isfreeze) {
        this.isfreeze = isfreeze == null ? null : isfreeze.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.FISSTART
     *
     * @return the value of T_LOG_WS_ORGANIZATION.FISSTART
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public String getFisstart() {
        return fisstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.FISSTART
     *
     * @param fisstart the value for T_LOG_WS_ORGANIZATION.FISSTART
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void setFisstart(String fisstart) {
        this.fisstart = fisstart == null ? null : fisstart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.FORGTYPESTR
     *
     * @return the value of T_LOG_WS_ORGANIZATION.FORGTYPESTR
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public String getForgtypestr() {
        return forgtypestr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.FORGTYPESTR
     *
     * @param forgtypestr the value for T_LOG_WS_ORGANIZATION.FORGTYPESTR
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void setForgtypestr(String forgtypestr) {
        this.forgtypestr = forgtypestr == null ? null : forgtypestr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.ISLEAF
     *
     * @return the value of T_LOG_WS_ORGANIZATION.ISLEAF
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public String getIsleaf() {
        return isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.ISLEAF
     *
     * @param isleaf the value for T_LOG_WS_ORGANIZATION.ISLEAF
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void setIsleaf(String isleaf) {
        this.isleaf = isleaf == null ? null : isleaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.FLEVEL
     *
     * @return the value of T_LOG_WS_ORGANIZATION.FLEVEL
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public Integer getFlevel() {
        return flevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.FLEVEL
     *
     * @param flevel the value for T_LOG_WS_ORGANIZATION.FLEVEL
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void setFlevel(Integer flevel) {
        this.flevel = flevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.DISPLAYNAME
     *
     * @return the value of T_LOG_WS_ORGANIZATION.DISPLAYNAME
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public String getDisplayname() {
        return displayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.DISPLAYNAME
     *
     * @param displayname the value for T_LOG_WS_ORGANIZATION.DISPLAYNAME
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void setDisplayname(String displayname) {
        this.displayname = displayname == null ? null : displayname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.DESCRIPTION
     *
     * @return the value of T_LOG_WS_ORGANIZATION.DESCRIPTION
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.DESCRIPTION
     *
     * @param description the value for T_LOG_WS_ORGANIZATION.DESCRIPTION
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.SIMPLENAME
     *
     * @return the value of T_LOG_WS_ORGANIZATION.SIMPLENAME
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public String getSimplename() {
        return simplename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.SIMPLENAME
     *
     * @param simplename the value for T_LOG_WS_ORGANIZATION.SIMPLENAME
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void setSimplename(String simplename) {
        this.simplename = simplename == null ? null : simplename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.RECDATE
     *
     * @return the value of T_LOG_WS_ORGANIZATION.RECDATE
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public Date getRecdate() {
        return recdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.RECDATE
     *
     * @param recdate the value for T_LOG_WS_ORGANIZATION.RECDATE
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void setRecdate(Date recdate) {
        this.recdate = recdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.T_LOG_BASEID
     *
     * @return the value of T_LOG_WS_ORGANIZATION.T_LOG_BASEID
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public Long gettLogBaseid() {
        return tLogBaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.T_LOG_BASEID
     *
     * @param tLogBaseid the value for T_LOG_WS_ORGANIZATION.T_LOG_BASEID
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void settLogBaseid(Long tLogBaseid) {
        this.tLogBaseid = tLogBaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.ISCOSTCENTER
     *
     * @return the value of T_LOG_WS_ORGANIZATION.ISCOSTCENTER
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public String getIscostcenter() {
        return iscostcenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.ISCOSTCENTER
     *
     * @param iscostcenter the value for T_LOG_WS_ORGANIZATION.ISCOSTCENTER
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void setIscostcenter(String iscostcenter) {
        this.iscostcenter = iscostcenter == null ? null : iscostcenter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_ORGANIZATION.PUSHTIME
     *
     * @return the value of T_LOG_WS_ORGANIZATION.PUSHTIME
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public Date getPushtime() {
        return pushtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_ORGANIZATION.PUSHTIME
     *
     * @param pushtime the value for T_LOG_WS_ORGANIZATION.PUSHTIME
     *
     * @mbggenerated Mon Mar 04 19:32:15 CST 2013
     */
    public void setPushtime(Date pushtime) {
        this.pushtime = pushtime;
    }
}