package com.creditease.eas.hr.bean;

import java.util.Date;

public class Wspersoninfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.ID
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.USERNAME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.LOGINNAME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.USEREMAIL
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String useremail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.USERACTIVE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String useractive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.USERORDERNO
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String userorderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.USERSTRYLE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String userstryle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.USERPASSWORD
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String userpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.USERCODE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String usercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.USERSEX
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String usersex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.BIRTHDAY
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.TELPHONE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.CELLPHONE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String cellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.TELEPHONEHOME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String telephonehome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.CERTTYPE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String certtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.CERTNUMBER
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String certnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.IDENTITYNO
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String identityno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.POSTCODE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.ADDRESS
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.COMMENTS
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.USERFAX
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String userfax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.REGISTERTIME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String registertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.ENTRYTIME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String entrytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.CITYNUMBER
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String citynumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.FNUMBER
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String fnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.ISMAINJOB
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String ismainjob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.DIRECTREPORTS
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String directreports;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.OPERATESIGN
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String operatesign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.OPERLOGINNAME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private String operloginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.CREATEDATE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.T_LOG_BASEID
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private Long tLogBaseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_WS_PERSONINFO.PUSHTIME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    private Date pushtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.ID
     *
     * @return the value of T_LOG_WS_PERSONINFO.ID
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.ID
     *
     * @param id the value for T_LOG_WS_PERSONINFO.ID
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.USERNAME
     *
     * @return the value of T_LOG_WS_PERSONINFO.USERNAME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.USERNAME
     *
     * @param username the value for T_LOG_WS_PERSONINFO.USERNAME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.LOGINNAME
     *
     * @return the value of T_LOG_WS_PERSONINFO.LOGINNAME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.LOGINNAME
     *
     * @param loginname the value for T_LOG_WS_PERSONINFO.LOGINNAME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.USEREMAIL
     *
     * @return the value of T_LOG_WS_PERSONINFO.USEREMAIL
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getUseremail() {
        return useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.USEREMAIL
     *
     * @param useremail the value for T_LOG_WS_PERSONINFO.USEREMAIL
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setUseremail(String useremail) {
        this.useremail = useremail == null ? null : useremail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.USERACTIVE
     *
     * @return the value of T_LOG_WS_PERSONINFO.USERACTIVE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getUseractive() {
        return useractive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.USERACTIVE
     *
     * @param useractive the value for T_LOG_WS_PERSONINFO.USERACTIVE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setUseractive(String useractive) {
        this.useractive = useractive == null ? null : useractive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.USERORDERNO
     *
     * @return the value of T_LOG_WS_PERSONINFO.USERORDERNO
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getUserorderno() {
        return userorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.USERORDERNO
     *
     * @param userorderno the value for T_LOG_WS_PERSONINFO.USERORDERNO
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setUserorderno(String userorderno) {
        this.userorderno = userorderno == null ? null : userorderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.USERSTRYLE
     *
     * @return the value of T_LOG_WS_PERSONINFO.USERSTRYLE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getUserstryle() {
        return userstryle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.USERSTRYLE
     *
     * @param userstryle the value for T_LOG_WS_PERSONINFO.USERSTRYLE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setUserstryle(String userstryle) {
        this.userstryle = userstryle == null ? null : userstryle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.USERPASSWORD
     *
     * @return the value of T_LOG_WS_PERSONINFO.USERPASSWORD
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.USERPASSWORD
     *
     * @param userpassword the value for T_LOG_WS_PERSONINFO.USERPASSWORD
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword == null ? null : userpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.USERCODE
     *
     * @return the value of T_LOG_WS_PERSONINFO.USERCODE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.USERCODE
     *
     * @param usercode the value for T_LOG_WS_PERSONINFO.USERCODE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode == null ? null : usercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.USERSEX
     *
     * @return the value of T_LOG_WS_PERSONINFO.USERSEX
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getUsersex() {
        return usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.USERSEX
     *
     * @param usersex the value for T_LOG_WS_PERSONINFO.USERSEX
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setUsersex(String usersex) {
        this.usersex = usersex == null ? null : usersex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.BIRTHDAY
     *
     * @return the value of T_LOG_WS_PERSONINFO.BIRTHDAY
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.BIRTHDAY
     *
     * @param birthday the value for T_LOG_WS_PERSONINFO.BIRTHDAY
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.TELPHONE
     *
     * @return the value of T_LOG_WS_PERSONINFO.TELPHONE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.TELPHONE
     *
     * @param telphone the value for T_LOG_WS_PERSONINFO.TELPHONE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.CELLPHONE
     *
     * @return the value of T_LOG_WS_PERSONINFO.CELLPHONE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.CELLPHONE
     *
     * @param cellphone the value for T_LOG_WS_PERSONINFO.CELLPHONE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone == null ? null : cellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.TELEPHONEHOME
     *
     * @return the value of T_LOG_WS_PERSONINFO.TELEPHONEHOME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getTelephonehome() {
        return telephonehome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.TELEPHONEHOME
     *
     * @param telephonehome the value for T_LOG_WS_PERSONINFO.TELEPHONEHOME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setTelephonehome(String telephonehome) {
        this.telephonehome = telephonehome == null ? null : telephonehome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.CERTTYPE
     *
     * @return the value of T_LOG_WS_PERSONINFO.CERTTYPE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getCerttype() {
        return certtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.CERTTYPE
     *
     * @param certtype the value for T_LOG_WS_PERSONINFO.CERTTYPE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setCerttype(String certtype) {
        this.certtype = certtype == null ? null : certtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.CERTNUMBER
     *
     * @return the value of T_LOG_WS_PERSONINFO.CERTNUMBER
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getCertnumber() {
        return certnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.CERTNUMBER
     *
     * @param certnumber the value for T_LOG_WS_PERSONINFO.CERTNUMBER
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setCertnumber(String certnumber) {
        this.certnumber = certnumber == null ? null : certnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.IDENTITYNO
     *
     * @return the value of T_LOG_WS_PERSONINFO.IDENTITYNO
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getIdentityno() {
        return identityno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.IDENTITYNO
     *
     * @param identityno the value for T_LOG_WS_PERSONINFO.IDENTITYNO
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setIdentityno(String identityno) {
        this.identityno = identityno == null ? null : identityno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.POSTCODE
     *
     * @return the value of T_LOG_WS_PERSONINFO.POSTCODE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.POSTCODE
     *
     * @param postcode the value for T_LOG_WS_PERSONINFO.POSTCODE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.ADDRESS
     *
     * @return the value of T_LOG_WS_PERSONINFO.ADDRESS
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.ADDRESS
     *
     * @param address the value for T_LOG_WS_PERSONINFO.ADDRESS
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.COMMENTS
     *
     * @return the value of T_LOG_WS_PERSONINFO.COMMENTS
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.COMMENTS
     *
     * @param comments the value for T_LOG_WS_PERSONINFO.COMMENTS
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.USERFAX
     *
     * @return the value of T_LOG_WS_PERSONINFO.USERFAX
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getUserfax() {
        return userfax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.USERFAX
     *
     * @param userfax the value for T_LOG_WS_PERSONINFO.USERFAX
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setUserfax(String userfax) {
        this.userfax = userfax == null ? null : userfax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.REGISTERTIME
     *
     * @return the value of T_LOG_WS_PERSONINFO.REGISTERTIME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.REGISTERTIME
     *
     * @param registertime the value for T_LOG_WS_PERSONINFO.REGISTERTIME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setRegistertime(String registertime) {
        this.registertime = registertime == null ? null : registertime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.ENTRYTIME
     *
     * @return the value of T_LOG_WS_PERSONINFO.ENTRYTIME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getEntrytime() {
        return entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.ENTRYTIME
     *
     * @param entrytime the value for T_LOG_WS_PERSONINFO.ENTRYTIME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setEntrytime(String entrytime) {
        this.entrytime = entrytime == null ? null : entrytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.CITYNUMBER
     *
     * @return the value of T_LOG_WS_PERSONINFO.CITYNUMBER
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getCitynumber() {
        return citynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.CITYNUMBER
     *
     * @param citynumber the value for T_LOG_WS_PERSONINFO.CITYNUMBER
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setCitynumber(String citynumber) {
        this.citynumber = citynumber == null ? null : citynumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.FNUMBER
     *
     * @return the value of T_LOG_WS_PERSONINFO.FNUMBER
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getFnumber() {
        return fnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.FNUMBER
     *
     * @param fnumber the value for T_LOG_WS_PERSONINFO.FNUMBER
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setFnumber(String fnumber) {
        this.fnumber = fnumber == null ? null : fnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.ISMAINJOB
     *
     * @return the value of T_LOG_WS_PERSONINFO.ISMAINJOB
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getIsmainjob() {
        return ismainjob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.ISMAINJOB
     *
     * @param ismainjob the value for T_LOG_WS_PERSONINFO.ISMAINJOB
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setIsmainjob(String ismainjob) {
        this.ismainjob = ismainjob == null ? null : ismainjob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.DIRECTREPORTS
     *
     * @return the value of T_LOG_WS_PERSONINFO.DIRECTREPORTS
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getDirectreports() {
        return directreports;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.DIRECTREPORTS
     *
     * @param directreports the value for T_LOG_WS_PERSONINFO.DIRECTREPORTS
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setDirectreports(String directreports) {
        this.directreports = directreports == null ? null : directreports.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.OPERATESIGN
     *
     * @return the value of T_LOG_WS_PERSONINFO.OPERATESIGN
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getOperatesign() {
        return operatesign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.OPERATESIGN
     *
     * @param operatesign the value for T_LOG_WS_PERSONINFO.OPERATESIGN
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setOperatesign(String operatesign) {
        this.operatesign = operatesign == null ? null : operatesign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.OPERLOGINNAME
     *
     * @return the value of T_LOG_WS_PERSONINFO.OPERLOGINNAME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public String getOperloginname() {
        return operloginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.OPERLOGINNAME
     *
     * @param operloginname the value for T_LOG_WS_PERSONINFO.OPERLOGINNAME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setOperloginname(String operloginname) {
        this.operloginname = operloginname == null ? null : operloginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.CREATEDATE
     *
     * @return the value of T_LOG_WS_PERSONINFO.CREATEDATE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.CREATEDATE
     *
     * @param createdate the value for T_LOG_WS_PERSONINFO.CREATEDATE
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.T_LOG_BASEID
     *
     * @return the value of T_LOG_WS_PERSONINFO.T_LOG_BASEID
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public Long gettLogBaseid() {
        return tLogBaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.T_LOG_BASEID
     *
     * @param tLogBaseid the value for T_LOG_WS_PERSONINFO.T_LOG_BASEID
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void settLogBaseid(Long tLogBaseid) {
        this.tLogBaseid = tLogBaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_WS_PERSONINFO.PUSHTIME
     *
     * @return the value of T_LOG_WS_PERSONINFO.PUSHTIME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public Date getPushtime() {
        return pushtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_WS_PERSONINFO.PUSHTIME
     *
     * @param pushtime the value for T_LOG_WS_PERSONINFO.PUSHTIME
     *
     * @mbggenerated Mon Mar 04 19:03:13 CST 2013
     */
    public void setPushtime(Date pushtime) {
        this.pushtime = pushtime;
    }
}