package com.creditease.eas.compliance.dao;

import java.util.List;
import java.util.Map;

import com.creditease.eas.compliance.bean.Complain;
import com.creditease.eas.compliance.bean.Inicasetype;
import com.creditease.eas.compliance.bean.excel.ComplainForExcel;
import com.creditease.eas.util.BaseDAO;

public interface ComplainMapper extends BaseDAO<Complain, Integer>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_COMPLAIN
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int insert(Complain record);
    /**
	 *根据主键查询信息
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    Complain selectByPrimaryKey(int record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_COMPLAIN
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int updateByPrimaryKey(Complain record);
    public List<Map> queryPageByParamss(Map map);
    /**
     * 根据id查询案件信息
     * @return
     */
	public Complain findCase(String fid);
	/**
	 * 
	 * 描述：根据案件信息id获得初步分类名称
	 * @return
	 */
	public List<Inicasetype> getInicaseTypeName(String fid);
	/**
	 * 根据案件id查询相关案件信息
	 * 描述：
	 * 2013-11-15 下午03:46:33 by sunxiaofeng
	 * @version
	 * @param fid
	 * @return
	 */
	Map findCaseById(String fid);
	
	/**
	 * 得到案件初步违归分类
	 */
	public List<ComplainForExcel> getIniNewCaseType(Map map);
	
	/**
	 * 得到案件申请结案违归分类
	 * @param map Map
	 * @return List<ComplainForExcel>
	 */
	public List<ComplainForExcel> getEndNewCaseType(Map map);
	
	/**
	 * 得到部门表
	 * @param map
	 * @return List<ComplainForExcel>
	 */
	public List<ComplainForExcel> getComplainDepartForExcels(Map map);
	
	/**
	 * 得到部门最大数
	 * @param map
	 * @return
	 */
	public int getComplainDepartMaxForExcel(Map map);
	
	/**
	 * 得到内部人员
	 * @param map
	 * @return List<ComplainForExcel>
	 */
	public List<ComplainForExcel> getComplainInnerPersonForExcels(Map map);
	
	/**
	 * 得到内部人员最大数
	 * @param map
	 * @return
	 */
	public int getComplainInnerPersonMaxForExcel(Map map);
	
	
	/**
	 * 得到收费信息
	 * @param map
	 * @return List<ComplainForExcel>
	 */
	public List<ComplainForExcel> getComplainChargeForExcels(Map map);
	
	/**
	 * 得到收费信息最大数
	 * @param map
	 * @return
	 */
	public int getComplainChargeMaxForExcel(Map map);
	
	/**
	 * 得到调查
	 */
	public List<ComplainForExcel> getComplainInvestigationForExcels(Map map);
	
	/**
	 * 保存反欺诈的数据到合规
	 * @param map
	 */
	int saveComplainToCompliance(Map map) throws Exception;
	
	/**
	 * 批量保存 从反欺诈传过来的中间表
	 * @param mapList
	 */
	int batchSaveLoanAnti(List<Map> mapList) throws Exception;
	
	/**
	 * 根据进件编号获取案子的数量
	 * @param code 
	 * @return
	 */
	int getComplainCountByComeIntoCount(String code);
	
	
}