package com.creditease.eas.compliance.dao;

import com.creditease.eas.compliance.bean.CompersonTemp;

public interface CompersonTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_COMPERSONTEMP
     *
     * @mbggenerated Sun Oct 20 16:52:14 CST 2013
     */
    int deleteByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_COMPERSONTEMP
     *
     * @mbggenerated Sun Oct 20 16:52:14 CST 2013
     */
    int insert(CompersonTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_COMPERSONTEMP
     *
     * @mbggenerated Sun Oct 20 16:52:14 CST 2013
     */
    int insertSelective(CompersonTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_COMPERSONTEMP
     *
     * @mbggenerated Sun Oct 20 16:52:14 CST 2013
     */
    CompersonTemp selectByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_COMPERSONTEMP
     *
     * @mbggenerated Sun Oct 20 16:52:14 CST 2013
     */
    int updateByPrimaryKeySelective(CompersonTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_COMPERSONTEMP
     *
     * @mbggenerated Sun Oct 20 16:52:14 CST 2013
     */
    int updateByPrimaryKey(CompersonTemp record);
}