package com.creditease.eas.compliance.dao;

import com.creditease.eas.compliance.bean.Cussource;

public interface CussourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_CUSSOURCE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int deleteByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_CUSSOURCE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int insert(Cussource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_CUSSOURCE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int insertSelective(Cussource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_CUSSOURCE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    Cussource selectByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_CUSSOURCE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int updateByPrimaryKeySelective(Cussource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_CUSSOURCE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int updateByPrimaryKey(Cussource record);
}