package com.creditease.eas.compliance.dao;

import com.creditease.eas.compliance.bean.Cusstatus;

public interface CusstatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_CUSSTATUS
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int deleteByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_CUSSTATUS
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int insert(Cusstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_CUSSTATUS
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int insertSelective(Cusstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_CUSSTATUS
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    Cusstatus selectByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_CUSSTATUS
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int updateByPrimaryKeySelective(Cusstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_CUSSTATUS
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int updateByPrimaryKey(Cusstatus record);
}