package com.creditease.eas.compliance.dao;

import com.creditease.eas.compliance.bean.Ditch;

public interface DitchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_DITCH
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int deleteByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_DITCH
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int insert(Ditch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_DITCH
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int insertSelective(Ditch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_DITCH
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    Ditch selectByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_DITCH
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int updateByPrimaryKeySelective(Ditch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_DITCH
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int updateByPrimaryKey(Ditch record);
}