package com.creditease.eas.compliance.dao;

import com.creditease.eas.compliance.bean.Evidencetype;

public interface EvidencetypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_EVIDENCETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int deleteByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_EVIDENCETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int insert(Evidencetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_EVIDENCETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int insertSelective(Evidencetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_EVIDENCETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    Evidencetype selectByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_EVIDENCETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int updateByPrimaryKeySelective(Evidencetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_EVIDENCETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int updateByPrimaryKey(Evidencetype record);
}