package com.creditease.eas.compliance.dao;

import com.creditease.eas.compliance.bean.Inicasetype;

public interface InicasetypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_INICASETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int deleteByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_INICASETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int insert(Inicasetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_INICASETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int insertSelective(Inicasetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_INICASETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    Inicasetype selectByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_INICASETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int updateByPrimaryKeySelective(Inicasetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_INICASETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int updateByPrimaryKey(Inicasetype record);
}