package com.creditease.eas.compliance.dao;

import java.util.List;

import com.creditease.eas.compliance.bean.Person;
import com.creditease.eas.compliance.bean.RelInicasetype;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_PERSON
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int deleteByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_PERSON
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_PERSON
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_PERSON
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    Person selectByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_PERSON
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int updateByPrimaryKeySelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_PERSON
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int updateByPrimaryKey(Person record);
    /**
     *根据案件id，查询关联的人员信息
     * @param complainid
     * @return
     * @throws Exception
     */
    public List<Person> selectPersonByComplainId(Integer complainid) throws Exception;
    /***
     *根据案件id，删除关联的人员信息
     * @param complainid
     * @return
     * @throws Exception
     */
    public int deletePersonByComplainId(Integer complainid) throws Exception;
}