package com.creditease.eas.compliance.dao;

import com.creditease.eas.compliance.bean.RelCompersonTemp;

public interface RelCompersonTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_REL_COMPERSON
     *
     * @mbggenerated Tue Oct 22 10:42:49 CST 2013
     */
    int deleteByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_REL_COMPERSON
     *
     * @mbggenerated Tue Oct 22 10:42:49 CST 2013
     */
    int insert(RelCompersonTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_REL_COMPERSON
     *
     * @mbggenerated Tue Oct 22 10:42:49 CST 2013
     */
    int insertSelective(RelCompersonTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_REL_COMPERSON
     *
     * @mbggenerated Tue Oct 22 10:42:49 CST 2013
     */
    RelCompersonTemp selectByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_REL_COMPERSON
     *
     * @mbggenerated Tue Oct 22 10:42:49 CST 2013
     */
    int updateByPrimaryKeySelective(RelCompersonTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_REL_COMPERSON
     *
     * @mbggenerated Tue Oct 22 10:42:49 CST 2013
     */
    int updateByPrimaryKey(RelCompersonTemp record);
}