package com.creditease.eas.compliance.dao;

import java.util.List;

import com.creditease.eas.compliance.bean.RelInicasetype;

public interface RelInicasetypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_REL_INICASETYPE
     *
     * @mbggenerated Tue Oct 22 16:37:52 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_REL_INICASETYPE
     *
     * @mbggenerated Tue Oct 22 16:37:52 CST 2013
     */
    int insert(RelInicasetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_REL_INICASETYPE
     *
     * @mbggenerated Tue Oct 22 16:37:52 CST 2013
     */
    int insertSelective(RelInicasetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_REL_INICASETYPE
     *
     * @mbggenerated Tue Oct 22 16:37:52 CST 2013
     */
    RelInicasetype selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_REL_INICASETYPE
     *
     * @mbggenerated Tue Oct 22 16:37:52 CST 2013
     */
    int updateByPrimaryKeySelective(RelInicasetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_REL_INICASETYPE
     *
     * @mbggenerated Tue Oct 22 16:37:52 CST 2013
     */
    int updateByPrimaryKey(RelInicasetype record);
    void deleteByApplysettlementId(int applysettlementId) throws Exception;
    /***
	 * 根据案件id，查询关联的案件的初步分类
	 * @param complainid
	 * @return
	 * @throws Exception
	 */
    public List<RelInicasetype> selectInicaseTypeByComplainId(Integer complainid) throws Exception;
    /***
	 * 根据案件id，删除关联的案件的初步分类
	 * @param complainid
	 * @return
	 * @throws Exception
	 */
    public int deleteInicaseTypeByComplainId(Integer complainid) throws Exception;
}