package com.creditease.eas.compliance.dao;

import com.creditease.eas.compliance.bean.Servicetype;

public interface ServicetypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_SERVICETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int deleteByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_SERVICETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int insert(Servicetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_SERVICETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int insertSelective(Servicetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_SERVICETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    Servicetype selectByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_SERVICETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int updateByPrimaryKeySelective(Servicetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COM_SERVICETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    int updateByPrimaryKey(Servicetype record);
}