package com.creditease.eas.admin.dao;

import java.util.List;
import java.util.Map;

import com.creditease.eas.admin.bean.AdminUserPort;
/***
 * 用户和接口人信息中间表
 * @Title:AdminUserPortMapper.java
 * @Package com.creditease.eas.admin.dao
 * created at 2014-5-30 上午11:32:10 by ygq
 * @author ygq
 * @version 1.0
 */
public interface AdminUserPortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_REL_USERPORT
     *
     * @mbggenerated Fri May 30 11:07:18 CST 2014
     */
    int deleteByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_REL_USERPORT
     *
     * @mbggenerated Fri May 30 11:07:18 CST 2014
     */
    int insert(AdminUserPort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_REL_USERPORT
     *
     * @mbggenerated Fri May 30 11:07:18 CST 2014
     */
    int insertSelective(AdminUserPort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_REL_USERPORT
     *
     * @mbggenerated Fri May 30 11:07:18 CST 2014
     */
    AdminUserPort selectByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_REL_USERPORT
     *
     * @mbggenerated Fri May 30 11:07:18 CST 2014
     */
    int updateByPrimaryKeySelective(AdminUserPort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_REL_USERPORT
     *
     * @mbggenerated Fri May 30 11:07:18 CST 2014
     */
    int updateByPrimaryKey(AdminUserPort record);
    /***
     * 根据用户id和接口人id，查询导入的权限是否已经存在了
    * @Title: findIfAuthorityExists
    *created at 2014-6-13 下午12:35:39 by ygq  
    * @param map
    * @return
    * @return int
     */
    int findIfAuthorityExists(Map map);
    /***
     * 根据用户id和接口人id，查询用户和接口人中间表的数据信息
    * @Title: findAuthorityByUserIdAndPortId
    *created at 2014-6-13 下午02:14:53 by ygq  
    * @param map
    * @return
    * @return AdminUserPort
     */
    AdminUserPort findAuthorityByUserIdAndPortId(Map map);
}