package com.creditease.eas.admin.dao;

import com.creditease.eas.admin.bean.AdminAuthority;
/**
 * 数据权限表对应的映射类
 * @Title:AdminAuthorityMapper.java
 * @Package com.creditease.eas.admin.dao
 * created at 2014-5-28 上午11:23:31 by ygq
 * @author ygq
 * @version 1.0
 */
public interface AdminAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_AUTHORITY
     *
     * @mbggenerated Wed May 28 09:08:12 CST 2014
     */
    int deleteByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_AUTHORITY
     *
     * @mbggenerated Wed May 28 09:08:12 CST 2014
     */
    int insert(AdminAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_AUTHORITY
     *
     * @mbggenerated Wed May 28 09:08:12 CST 2014
     */
    int insertSelective(AdminAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_AUTHORITY
     *
     * @mbggenerated Wed May 28 09:08:12 CST 2014
     */
    AdminAuthority selectByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_AUTHORITY
     *
     * @mbggenerated Wed May 28 09:08:12 CST 2014
     */
    int updateByPrimaryKeySelective(AdminAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_AUTHORITY
     *
     * @mbggenerated Wed May 28 09:08:12 CST 2014
     */
    int updateByPrimaryKey(AdminAuthority record);
}