package com.creditease.eas.admin.dao;

import java.util.List;
import java.util.Map;

import com.creditease.eas.admin.bean.AdminUserPort;
import com.creditease.eas.admin.bean.UserRole;
import com.creditease.eas.util.BaseDAO;

public interface UserRoleMapper extends BaseDAO<UserRole, Integer>{
    /**
     * 根据用户id删除中间表中用户角色
     */
    int deleteByPrimaryKey(Integer id);

    
    
    /**
     * 插入用户角色
     * 描述：
     * 2013-8-23 上午11:34:08 by Administrator
     * @version
     * @param record
     * @return
     */
    int insertUserRole(UserRole record);

    /**
     * 删除数据时 stutas字段为1
     * 描述：
     * 2013-8-19 下午07:21:23 by Administrator
     * @version
     * @param id
     */
    public void updateStatus(Integer id);
    
   /**
    * 当前用户角色id集合
    * 描述：
    * 2013-8-23 下午01:50:56 by Administrator
    * @version
    * @param id
    * @return
    */
    public List<Integer> userroleidlist(Integer id);
    
    /**
     * 
     * 描述：当前用户的角色id
     * 2013-10-9 下午05:59:08 by zhangxin
     * @version
     * @param id
     * @return
     */
    public int userroleid(Integer id);
    
    /**
     * 查询用户id的集合
     * 描述：
     * 2013-8-29 下午03:00:14 by Administrator
     * @version
     * @return
     */
    public List<Integer> useridset();
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrole
     *
     * @mbggenerated Tue Aug 06 23:10:32 CST 2013
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrole
     *
     * @mbggenerated Tue Aug 06 23:10:32 CST 2013
     */
    UserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrole
     *
     * @mbggenerated Tue Aug 06 23:10:32 CST 2013
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrole
     *
     * @mbggenerated Tue Aug 06 23:10:32 CST 2013
     */
    int updateByPrimaryKey(UserRole record);
    /***
     * 根据用户id和角色id删除角色权限信息
    * @Title: deleteUserRoleByUseridAndRoleId
    *created at 2014-6-13 下午02:52:22 by ygq  
    * @param userid
    * @param roleid
    * @return
    * @return int
     */
    int deleteUserRoleByUseridAndRoleId(Map map);
    
    /***
     * 根据用户id和角色id，查询用户和角色的数据信息
    * @Title: findAuthorityByUserIdAndPortId
    *created at 2014-6-13 下午02:14:53 by ygq  
    * @param map
    * @return
    * @return AdminUserPort
     */
    UserRole findUserRoleByUserIdAndRole(Map map);
}