package com.creditease.eas.admin.dao;

import com.creditease.eas.admin.bean.User;
import com.creditease.eas.util.BaseDAO;

import java.util.List;
import java.util.Map;

public interface UserMapper extends BaseDAO<User, Integer>{
   
	/**
	 * 插入用户
	 * 描述：
	 * 2013-8-23 上午10:36:50 by Administrator
	 * @version
	 * @param user
	 * @return
	 */
	public int insertUser(User user);
	
	 /**
     * 删除数据时 stutas字段为1
     * 描述：
     * 2013-8-19 下午07:21:23 by Administrator
     * @version
     * @param id
     */
    public void updateStatus(Integer id);
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbggenerated Wed Jan 16 14:21:23 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbggenerated Wed Jan 16 14:21:23 CST 2013
     */
    int insertSelective(User user);
    /**
     * 
     * 描述：根据用户名和密码查询用户
     * 2013-1-16 下午02:26:22 by ygq
     * @version
     * @param map
     * @return
     */
    User selectByNameAndPassword(Map<String, String> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbggenerated Wed Jan 16 14:21:23 CST 2013
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbggenerated Wed Jan 16 14:21:23 CST 2013
     */
    int updateByPrimaryKey(User record);
    /**
     * 
     * 描述：判断用户是否已经存在
     * 2013-1-17 下午12:36:14 by ygq
     * @version
     * @param username
     * @return
     */
    int selectedIfUserExists(String username);
    
    /**
     * 查询所有正常状态的用户
     * 描述：
     * 2013-8-29 下午02:41:47 by Administrator
     * @version
     * @return
     */
   public List<User> seleUserList();
   /***
    * 根据用户名，查用户的基本信息和角色信息
   * @Title: selectedUserAndRoleInfoByUserName
   *created at 2014-6-1 下午02:10:23 by ygq  
   * @param username
   * @return
   * @return Map<String,Object>
    */
   public List<Map<String,Object>> selectedUserAndRoleInfoByUserName(String username);
   /**
    * 根据用户名，查询用户信息
   * @Title: selectOneUserByUsername
   *created at 2014-6-13 下午02:44:13 by ygq  
   * @param username
   * @return
   * @return User
    */
   public User selectOneUserByUsername(String username);
   
    
}