package com.creditease.eas.warn.bean;

import java.util.Date;

public class FinanceGroupBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.id
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.name
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.creator
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.creatortime
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    private Date creatortime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.lastupdater
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    private String lastupdater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.lastupdatetime
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    private String lastupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.ext1
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.ext2
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    private String ext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.ext3
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    private String ext3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.ext4
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    private String ext4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.ext5
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    private String ext5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.ext6
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    private String ext6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.ext7
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    private String ext7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.ext8
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    private String ext8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.ext9
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    private String ext9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.ext10
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    private String ext10;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.id
     *
     * @return the value of t_finance_group.id
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.id
     *
     * @param id the value for t_finance_group.id
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.name
     *
     * @return the value of t_finance_group.name
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.name
     *
     * @param name the value for t_finance_group.name
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.creator
     *
     * @return the value of t_finance_group.creator
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.creator
     *
     * @param creator the value for t_finance_group.creator
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.creatortime
     *
     * @return the value of t_finance_group.creatortime
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public Date getCreatortime() {
        return creatortime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.creatortime
     *
     * @param creatortime the value for t_finance_group.creatortime
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public void setCreatortime(Date creatortime) {
        this.creatortime = creatortime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.lastupdater
     *
     * @return the value of t_finance_group.lastupdater
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public String getLastupdater() {
        return lastupdater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.lastupdater
     *
     * @param lastupdater the value for t_finance_group.lastupdater
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public void setLastupdater(String lastupdater) {
        this.lastupdater = lastupdater == null ? null : lastupdater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.lastupdatetime
     *
     * @return the value of t_finance_group.lastupdatetime
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public String getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.lastupdatetime
     *
     * @param lastupdatetime the value for t_finance_group.lastupdatetime
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public void setLastupdatetime(String lastupdatetime) {
        this.lastupdatetime = lastupdatetime == null ? null : lastupdatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.ext1
     *
     * @return the value of t_finance_group.ext1
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.ext1
     *
     * @param ext1 the value for t_finance_group.ext1
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.ext2
     *
     * @return the value of t_finance_group.ext2
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.ext2
     *
     * @param ext2 the value for t_finance_group.ext2
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.ext3
     *
     * @return the value of t_finance_group.ext3
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.ext3
     *
     * @param ext3 the value for t_finance_group.ext3
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.ext4
     *
     * @return the value of t_finance_group.ext4
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public String getExt4() {
        return ext4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.ext4
     *
     * @param ext4 the value for t_finance_group.ext4
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public void setExt4(String ext4) {
        this.ext4 = ext4 == null ? null : ext4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.ext5
     *
     * @return the value of t_finance_group.ext5
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public String getExt5() {
        return ext5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.ext5
     *
     * @param ext5 the value for t_finance_group.ext5
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public void setExt5(String ext5) {
        this.ext5 = ext5 == null ? null : ext5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.ext6
     *
     * @return the value of t_finance_group.ext6
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public String getExt6() {
        return ext6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.ext6
     *
     * @param ext6 the value for t_finance_group.ext6
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public void setExt6(String ext6) {
        this.ext6 = ext6 == null ? null : ext6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.ext7
     *
     * @return the value of t_finance_group.ext7
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public String getExt7() {
        return ext7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.ext7
     *
     * @param ext7 the value for t_finance_group.ext7
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public void setExt7(String ext7) {
        this.ext7 = ext7 == null ? null : ext7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.ext8
     *
     * @return the value of t_finance_group.ext8
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public String getExt8() {
        return ext8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.ext8
     *
     * @param ext8 the value for t_finance_group.ext8
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public void setExt8(String ext8) {
        this.ext8 = ext8 == null ? null : ext8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.ext9
     *
     * @return the value of t_finance_group.ext9
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public String getExt9() {
        return ext9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.ext9
     *
     * @param ext9 the value for t_finance_group.ext9
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public void setExt9(String ext9) {
        this.ext9 = ext9 == null ? null : ext9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.ext10
     *
     * @return the value of t_finance_group.ext10
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public String getExt10() {
        return ext10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.ext10
     *
     * @param ext10 the value for t_finance_group.ext10
     *
     * @mbggenerated Mon Sep 16 14:45:42 CST 2013
     */
    public void setExt10(String ext10) {
        this.ext10 = ext10 == null ? null : ext10.trim();
    }
}