package com.creditease.eas.warn.bean;

import java.util.Date;

public class Jumbosmsv {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.ID
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.NAME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.JUMTYPE
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private Integer jumtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.SENDWAY
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private Integer sendway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.CONTENT
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.FOUNDER
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String founder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.CREATIME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private Date creatime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.ALTERMAN
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String alterman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.ALTERTIME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private Date altertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.VARID
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private Integer varid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.EXT1
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.EXT2
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.EXT3
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.EXT4
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.EXT5
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.EXT6
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.EXT7
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.EXT8
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.EXT9
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JUMBOSMSV.EXT10
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext10;

    
    private Integer isuse;
    
    
    public Integer getIsuse() {
		return isuse;
	}

	public void setIsuse(Integer isuse) {
		this.isuse = isuse;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.ID
     *
     * @return the value of T_JUMBOSMSV.ID
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.ID
     *
     * @param id the value for T_JUMBOSMSV.ID
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.NAME
     *
     * @return the value of T_JUMBOSMSV.NAME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.NAME
     *
     * @param name the value for T_JUMBOSMSV.NAME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.JUMTYPE
     *
     * @return the value of T_JUMBOSMSV.JUMTYPE
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public Integer getJumtype() {
        return jumtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.JUMTYPE
     *
     * @param jumtype the value for T_JUMBOSMSV.JUMTYPE
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setJumtype(Integer jumtype) {
        this.jumtype = jumtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.SENDWAY
     *
     * @return the value of T_JUMBOSMSV.SENDWAY
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public Integer getSendway() {
        return sendway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.SENDWAY
     *
     * @param sendway the value for T_JUMBOSMSV.SENDWAY
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setSendway(Integer sendway) {
        this.sendway = sendway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.CONTENT
     *
     * @return the value of T_JUMBOSMSV.CONTENT
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.CONTENT
     *
     * @param content the value for T_JUMBOSMSV.CONTENT
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.FOUNDER
     *
     * @return the value of T_JUMBOSMSV.FOUNDER
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getFounder() {
        return founder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.FOUNDER
     *
     * @param founder the value for T_JUMBOSMSV.FOUNDER
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setFounder(String founder) {
        this.founder = founder == null ? null : founder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.CREATIME
     *
     * @return the value of T_JUMBOSMSV.CREATIME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public Date getCreatime() {
        return creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.CREATIME
     *
     * @param creatime the value for T_JUMBOSMSV.CREATIME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setCreatime(Date creatime) {
        this.creatime = creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.ALTERMAN
     *
     * @return the value of T_JUMBOSMSV.ALTERMAN
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getAlterman() {
        return alterman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.ALTERMAN
     *
     * @param alterman the value for T_JUMBOSMSV.ALTERMAN
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setAlterman(String alterman) {
        this.alterman = alterman == null ? null : alterman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.ALTERTIME
     *
     * @return the value of T_JUMBOSMSV.ALTERTIME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public Date getAltertime() {
        return altertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.ALTERTIME
     *
     * @param altertime the value for T_JUMBOSMSV.ALTERTIME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setAltertime(Date altertime) {
        this.altertime = altertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.VARID
     *
     * @return the value of T_JUMBOSMSV.VARID
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public Integer getVarid() {
        return varid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.VARID
     *
     * @param varid the value for T_JUMBOSMSV.VARID
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setVarid(Integer varid) {
        this.varid = varid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.EXT1
     *
     * @return the value of T_JUMBOSMSV.EXT1
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.EXT1
     *
     * @param ext1 the value for T_JUMBOSMSV.EXT1
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.EXT2
     *
     * @return the value of T_JUMBOSMSV.EXT2
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.EXT2
     *
     * @param ext2 the value for T_JUMBOSMSV.EXT2
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.EXT3
     *
     * @return the value of T_JUMBOSMSV.EXT3
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.EXT3
     *
     * @param ext3 the value for T_JUMBOSMSV.EXT3
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.EXT4
     *
     * @return the value of T_JUMBOSMSV.EXT4
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt4() {
        return ext4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.EXT4
     *
     * @param ext4 the value for T_JUMBOSMSV.EXT4
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt4(String ext4) {
        this.ext4 = ext4 == null ? null : ext4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.EXT5
     *
     * @return the value of T_JUMBOSMSV.EXT5
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt5() {
        return ext5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.EXT5
     *
     * @param ext5 the value for T_JUMBOSMSV.EXT5
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt5(String ext5) {
        this.ext5 = ext5 == null ? null : ext5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.EXT6
     *
     * @return the value of T_JUMBOSMSV.EXT6
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt6() {
        return ext6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.EXT6
     *
     * @param ext6 the value for T_JUMBOSMSV.EXT6
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt6(String ext6) {
        this.ext6 = ext6 == null ? null : ext6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.EXT7
     *
     * @return the value of T_JUMBOSMSV.EXT7
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt7() {
        return ext7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.EXT7
     *
     * @param ext7 the value for T_JUMBOSMSV.EXT7
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt7(String ext7) {
        this.ext7 = ext7 == null ? null : ext7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.EXT8
     *
     * @return the value of T_JUMBOSMSV.EXT8
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt8() {
        return ext8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.EXT8
     *
     * @param ext8 the value for T_JUMBOSMSV.EXT8
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt8(String ext8) {
        this.ext8 = ext8 == null ? null : ext8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.EXT9
     *
     * @return the value of T_JUMBOSMSV.EXT9
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt9() {
        return ext9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.EXT9
     *
     * @param ext9 the value for T_JUMBOSMSV.EXT9
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt9(String ext9) {
        this.ext9 = ext9 == null ? null : ext9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JUMBOSMSV.EXT10
     *
     * @return the value of T_JUMBOSMSV.EXT10
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt10() {
        return ext10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JUMBOSMSV.EXT10
     *
     * @param ext10 the value for T_JUMBOSMSV.EXT10
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt10(String ext10) {
        this.ext10 = ext10 == null ? null : ext10.trim();
    }
}