package com.creditease.eas.warn.bean;

public class PersonData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.DTID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private Long dtid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.LOGINNAME
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.NAME
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.ID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.PERSONNUMBER
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String personnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.ENTERDATE
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String enterdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.GENDER
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.BIRTHDAY
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.EMAIL
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.ADDRESS
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.HOMEPHONE
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String homephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.CELL
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String cell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.IDCARDNO
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String idcardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.PASSPORTNO
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String passportno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.NATIVEPLACEID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String nativeplaceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.FEMPLOYEETYPEID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String femployeetypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.FEMPLOYEECLASSIFYID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String femployeeclassifyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.FINDEX
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private Integer findex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.FFULLNAMEPINGYIN
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String ffullnamepingyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.CFWORKPLACEID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String cfworkplaceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.CFZLID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String cfzlid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.CFZCID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String cfzcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.CFRZZGID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String cfrzzgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.CFGANGWEISHUOMINGID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String cfgangweishuomingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.CFSHUOMINGSHU
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String cfshuomingshu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.CFBANGONGDI
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String cfbangongdi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.POSITIONID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String positionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.ORGID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String orgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.ORGNUMBER
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String orgnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.POSITIONNAME
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String positionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERSONDATA.ORGNAME
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    private String orgname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.DTID
     *
     * @return the value of T_PERSONDATA.DTID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public Long getDtid() {
        return dtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.DTID
     *
     * @param dtid the value for T_PERSONDATA.DTID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setDtid(Long dtid) {
        this.dtid = dtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.LOGINNAME
     *
     * @return the value of T_PERSONDATA.LOGINNAME
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.LOGINNAME
     *
     * @param loginname the value for T_PERSONDATA.LOGINNAME
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.NAME
     *
     * @return the value of T_PERSONDATA.NAME
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.NAME
     *
     * @param name the value for T_PERSONDATA.NAME
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.ID
     *
     * @return the value of T_PERSONDATA.ID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.ID
     *
     * @param id the value for T_PERSONDATA.ID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.PERSONNUMBER
     *
     * @return the value of T_PERSONDATA.PERSONNUMBER
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getPersonnumber() {
        return personnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.PERSONNUMBER
     *
     * @param personnumber the value for T_PERSONDATA.PERSONNUMBER
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setPersonnumber(String personnumber) {
        this.personnumber = personnumber == null ? null : personnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.ENTERDATE
     *
     * @return the value of T_PERSONDATA.ENTERDATE
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getEnterdate() {
        return enterdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.ENTERDATE
     *
     * @param enterdate the value for T_PERSONDATA.ENTERDATE
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setEnterdate(String enterdate) {
        this.enterdate = enterdate == null ? null : enterdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.GENDER
     *
     * @return the value of T_PERSONDATA.GENDER
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.GENDER
     *
     * @param gender the value for T_PERSONDATA.GENDER
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.BIRTHDAY
     *
     * @return the value of T_PERSONDATA.BIRTHDAY
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.BIRTHDAY
     *
     * @param birthday the value for T_PERSONDATA.BIRTHDAY
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.EMAIL
     *
     * @return the value of T_PERSONDATA.EMAIL
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.EMAIL
     *
     * @param email the value for T_PERSONDATA.EMAIL
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.ADDRESS
     *
     * @return the value of T_PERSONDATA.ADDRESS
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.ADDRESS
     *
     * @param address the value for T_PERSONDATA.ADDRESS
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.HOMEPHONE
     *
     * @return the value of T_PERSONDATA.HOMEPHONE
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getHomephone() {
        return homephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.HOMEPHONE
     *
     * @param homephone the value for T_PERSONDATA.HOMEPHONE
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setHomephone(String homephone) {
        this.homephone = homephone == null ? null : homephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.CELL
     *
     * @return the value of T_PERSONDATA.CELL
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getCell() {
        return cell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.CELL
     *
     * @param cell the value for T_PERSONDATA.CELL
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setCell(String cell) {
        this.cell = cell == null ? null : cell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.IDCARDNO
     *
     * @return the value of T_PERSONDATA.IDCARDNO
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getIdcardno() {
        return idcardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.IDCARDNO
     *
     * @param idcardno the value for T_PERSONDATA.IDCARDNO
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setIdcardno(String idcardno) {
        this.idcardno = idcardno == null ? null : idcardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.PASSPORTNO
     *
     * @return the value of T_PERSONDATA.PASSPORTNO
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getPassportno() {
        return passportno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.PASSPORTNO
     *
     * @param passportno the value for T_PERSONDATA.PASSPORTNO
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setPassportno(String passportno) {
        this.passportno = passportno == null ? null : passportno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.NATIVEPLACEID
     *
     * @return the value of T_PERSONDATA.NATIVEPLACEID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getNativeplaceid() {
        return nativeplaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.NATIVEPLACEID
     *
     * @param nativeplaceid the value for T_PERSONDATA.NATIVEPLACEID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setNativeplaceid(String nativeplaceid) {
        this.nativeplaceid = nativeplaceid == null ? null : nativeplaceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.FEMPLOYEETYPEID
     *
     * @return the value of T_PERSONDATA.FEMPLOYEETYPEID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getFemployeetypeid() {
        return femployeetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.FEMPLOYEETYPEID
     *
     * @param femployeetypeid the value for T_PERSONDATA.FEMPLOYEETYPEID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setFemployeetypeid(String femployeetypeid) {
        this.femployeetypeid = femployeetypeid == null ? null : femployeetypeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.FEMPLOYEECLASSIFYID
     *
     * @return the value of T_PERSONDATA.FEMPLOYEECLASSIFYID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getFemployeeclassifyid() {
        return femployeeclassifyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.FEMPLOYEECLASSIFYID
     *
     * @param femployeeclassifyid the value for T_PERSONDATA.FEMPLOYEECLASSIFYID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setFemployeeclassifyid(String femployeeclassifyid) {
        this.femployeeclassifyid = femployeeclassifyid == null ? null : femployeeclassifyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.FINDEX
     *
     * @return the value of T_PERSONDATA.FINDEX
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public Integer getFindex() {
        return findex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.FINDEX
     *
     * @param findex the value for T_PERSONDATA.FINDEX
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setFindex(Integer findex) {
        this.findex = findex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.FFULLNAMEPINGYIN
     *
     * @return the value of T_PERSONDATA.FFULLNAMEPINGYIN
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getFfullnamepingyin() {
        return ffullnamepingyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.FFULLNAMEPINGYIN
     *
     * @param ffullnamepingyin the value for T_PERSONDATA.FFULLNAMEPINGYIN
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setFfullnamepingyin(String ffullnamepingyin) {
        this.ffullnamepingyin = ffullnamepingyin == null ? null : ffullnamepingyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.CFWORKPLACEID
     *
     * @return the value of T_PERSONDATA.CFWORKPLACEID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getCfworkplaceid() {
        return cfworkplaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.CFWORKPLACEID
     *
     * @param cfworkplaceid the value for T_PERSONDATA.CFWORKPLACEID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setCfworkplaceid(String cfworkplaceid) {
        this.cfworkplaceid = cfworkplaceid == null ? null : cfworkplaceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.CFZLID
     *
     * @return the value of T_PERSONDATA.CFZLID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getCfzlid() {
        return cfzlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.CFZLID
     *
     * @param cfzlid the value for T_PERSONDATA.CFZLID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setCfzlid(String cfzlid) {
        this.cfzlid = cfzlid == null ? null : cfzlid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.CFZCID
     *
     * @return the value of T_PERSONDATA.CFZCID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getCfzcid() {
        return cfzcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.CFZCID
     *
     * @param cfzcid the value for T_PERSONDATA.CFZCID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setCfzcid(String cfzcid) {
        this.cfzcid = cfzcid == null ? null : cfzcid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.CFRZZGID
     *
     * @return the value of T_PERSONDATA.CFRZZGID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getCfrzzgid() {
        return cfrzzgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.CFRZZGID
     *
     * @param cfrzzgid the value for T_PERSONDATA.CFRZZGID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setCfrzzgid(String cfrzzgid) {
        this.cfrzzgid = cfrzzgid == null ? null : cfrzzgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.CFGANGWEISHUOMINGID
     *
     * @return the value of T_PERSONDATA.CFGANGWEISHUOMINGID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getCfgangweishuomingid() {
        return cfgangweishuomingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.CFGANGWEISHUOMINGID
     *
     * @param cfgangweishuomingid the value for T_PERSONDATA.CFGANGWEISHUOMINGID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setCfgangweishuomingid(String cfgangweishuomingid) {
        this.cfgangweishuomingid = cfgangweishuomingid == null ? null : cfgangweishuomingid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.CFSHUOMINGSHU
     *
     * @return the value of T_PERSONDATA.CFSHUOMINGSHU
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getCfshuomingshu() {
        return cfshuomingshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.CFSHUOMINGSHU
     *
     * @param cfshuomingshu the value for T_PERSONDATA.CFSHUOMINGSHU
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setCfshuomingshu(String cfshuomingshu) {
        this.cfshuomingshu = cfshuomingshu == null ? null : cfshuomingshu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.CFBANGONGDI
     *
     * @return the value of T_PERSONDATA.CFBANGONGDI
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getCfbangongdi() {
        return cfbangongdi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.CFBANGONGDI
     *
     * @param cfbangongdi the value for T_PERSONDATA.CFBANGONGDI
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setCfbangongdi(String cfbangongdi) {
        this.cfbangongdi = cfbangongdi == null ? null : cfbangongdi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.POSITIONID
     *
     * @return the value of T_PERSONDATA.POSITIONID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getPositionid() {
        return positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.POSITIONID
     *
     * @param positionid the value for T_PERSONDATA.POSITIONID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setPositionid(String positionid) {
        this.positionid = positionid == null ? null : positionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.ORGID
     *
     * @return the value of T_PERSONDATA.ORGID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.ORGID
     *
     * @param orgid the value for T_PERSONDATA.ORGID
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.ORGNUMBER
     *
     * @return the value of T_PERSONDATA.ORGNUMBER
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getOrgnumber() {
        return orgnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.ORGNUMBER
     *
     * @param orgnumber the value for T_PERSONDATA.ORGNUMBER
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setOrgnumber(String orgnumber) {
        this.orgnumber = orgnumber == null ? null : orgnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.POSITIONNAME
     *
     * @return the value of T_PERSONDATA.POSITIONNAME
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getPositionname() {
        return positionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.POSITIONNAME
     *
     * @param positionname the value for T_PERSONDATA.POSITIONNAME
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setPositionname(String positionname) {
        this.positionname = positionname == null ? null : positionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERSONDATA.ORGNAME
     *
     * @return the value of T_PERSONDATA.ORGNAME
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERSONDATA.ORGNAME
     *
     * @param orgname the value for T_PERSONDATA.ORGNAME
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }
}