package com.creditease.eas.warn.bean;

import java.math.BigDecimal;
import java.util.Date;

public class personContactMethod {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private String fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FHOMEPLACE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fhomeplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FEMAIL
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object femail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FCREATORID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private String fcreatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FCREATETIME
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Date fcreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FLASTUPDATEUSERID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private String flastupdateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FLASTUPDATETIME
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Date flastupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FWORKAREA
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private String fworkarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FOFFICEPHONE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fofficephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FHOMEPHONE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fhomephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FMOBILE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fmobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FADDRESS
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object faddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FHOMEADDRESS
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fhomeaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FPOSTALCODE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fpostalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FPERSONID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private String fpersonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FHRORGUNITID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private String fhrorgunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FCONTROLUNITID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private String fcontrolunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FHJADDRESS
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fhjaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FIDCARDADDRESS
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fidcardaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FBACKUPEMAIL
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fbackupemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FBACKUPMOBILE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fbackupmobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FREGRESIDENCEID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fregresidenceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FHUKOUKINGID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private String fhukoukingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FMSN
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fmsn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FQQ
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fqq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FBACKUPOFFICEPHONE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fbackupofficephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FBACKUPHOMEPHONE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fbackuphomephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY1
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private String fzdy1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY2
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private String fzdy2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY3
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private String fzdy3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY4
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private String fzdy4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY5
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private String fzdy5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY6
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private String fzdy6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY7
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private String fzdy7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY8
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private String fzdy8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY9
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Date fzdy9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY10
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Date fzdy10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY11
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Date fzdy11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY12
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Date fzdy12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY13
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Date fzdy13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY14
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Date fzdy14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY15
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fzdy15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY16
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fzdy16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY17
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fzdy17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY18
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private BigDecimal fzdy18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY19
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private BigDecimal fzdy19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY20
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Long fzdy20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY21
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Long fzdy21;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY23
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fzdy23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY24
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fzdy24;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY25
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fzdy25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY26
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Long fzdy26;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.FZDY22
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object fzdy22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.CFMAIL
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object cfmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.CFPRIMAIL
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object cfprimail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.CFHJPOST
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object cfhjpost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.CFNADDRESS
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object cfnaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.CFNADDRESSPOST
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private Object cfnaddresspost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HR_PERSONCONTACTMETHOD.CFHUKOULEIXINGID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    private String cfhukouleixingid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FID
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FID
     *
     * @param fid the value for T_HR_PERSONCONTACTMETHOD.FID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FHOMEPLACE
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FHOMEPLACE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFhomeplace() {
        return fhomeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FHOMEPLACE
     *
     * @param fhomeplace the value for T_HR_PERSONCONTACTMETHOD.FHOMEPLACE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFhomeplace(Object fhomeplace) {
        this.fhomeplace = fhomeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FEMAIL
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FEMAIL
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFemail() {
        return femail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FEMAIL
     *
     * @param femail the value for T_HR_PERSONCONTACTMETHOD.FEMAIL
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFemail(Object femail) {
        this.femail = femail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FCREATORID
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FCREATORID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public String getFcreatorid() {
        return fcreatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FCREATORID
     *
     * @param fcreatorid the value for T_HR_PERSONCONTACTMETHOD.FCREATORID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFcreatorid(String fcreatorid) {
        this.fcreatorid = fcreatorid == null ? null : fcreatorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FCREATETIME
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FCREATETIME
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Date getFcreatetime() {
        return fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FCREATETIME
     *
     * @param fcreatetime the value for T_HR_PERSONCONTACTMETHOD.FCREATETIME
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFcreatetime(Date fcreatetime) {
        this.fcreatetime = fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FLASTUPDATEUSERID
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FLASTUPDATEUSERID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public String getFlastupdateuserid() {
        return flastupdateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FLASTUPDATEUSERID
     *
     * @param flastupdateuserid the value for T_HR_PERSONCONTACTMETHOD.FLASTUPDATEUSERID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFlastupdateuserid(String flastupdateuserid) {
        this.flastupdateuserid = flastupdateuserid == null ? null : flastupdateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FLASTUPDATETIME
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FLASTUPDATETIME
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Date getFlastupdatetime() {
        return flastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FLASTUPDATETIME
     *
     * @param flastupdatetime the value for T_HR_PERSONCONTACTMETHOD.FLASTUPDATETIME
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFlastupdatetime(Date flastupdatetime) {
        this.flastupdatetime = flastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FWORKAREA
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FWORKAREA
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public String getFworkarea() {
        return fworkarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FWORKAREA
     *
     * @param fworkarea the value for T_HR_PERSONCONTACTMETHOD.FWORKAREA
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFworkarea(String fworkarea) {
        this.fworkarea = fworkarea == null ? null : fworkarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FOFFICEPHONE
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FOFFICEPHONE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFofficephone() {
        return fofficephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FOFFICEPHONE
     *
     * @param fofficephone the value for T_HR_PERSONCONTACTMETHOD.FOFFICEPHONE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFofficephone(Object fofficephone) {
        this.fofficephone = fofficephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FHOMEPHONE
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FHOMEPHONE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFhomephone() {
        return fhomephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FHOMEPHONE
     *
     * @param fhomephone the value for T_HR_PERSONCONTACTMETHOD.FHOMEPHONE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFhomephone(Object fhomephone) {
        this.fhomephone = fhomephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FMOBILE
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FMOBILE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFmobile() {
        return fmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FMOBILE
     *
     * @param fmobile the value for T_HR_PERSONCONTACTMETHOD.FMOBILE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFmobile(Object fmobile) {
        this.fmobile = fmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FADDRESS
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FADDRESS
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFaddress() {
        return faddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FADDRESS
     *
     * @param faddress the value for T_HR_PERSONCONTACTMETHOD.FADDRESS
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFaddress(Object faddress) {
        this.faddress = faddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FHOMEADDRESS
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FHOMEADDRESS
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFhomeaddress() {
        return fhomeaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FHOMEADDRESS
     *
     * @param fhomeaddress the value for T_HR_PERSONCONTACTMETHOD.FHOMEADDRESS
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFhomeaddress(Object fhomeaddress) {
        this.fhomeaddress = fhomeaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FPOSTALCODE
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FPOSTALCODE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFpostalcode() {
        return fpostalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FPOSTALCODE
     *
     * @param fpostalcode the value for T_HR_PERSONCONTACTMETHOD.FPOSTALCODE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFpostalcode(Object fpostalcode) {
        this.fpostalcode = fpostalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FPERSONID
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FPERSONID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public String getFpersonid() {
        return fpersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FPERSONID
     *
     * @param fpersonid the value for T_HR_PERSONCONTACTMETHOD.FPERSONID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFpersonid(String fpersonid) {
        this.fpersonid = fpersonid == null ? null : fpersonid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FHRORGUNITID
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FHRORGUNITID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public String getFhrorgunitid() {
        return fhrorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FHRORGUNITID
     *
     * @param fhrorgunitid the value for T_HR_PERSONCONTACTMETHOD.FHRORGUNITID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFhrorgunitid(String fhrorgunitid) {
        this.fhrorgunitid = fhrorgunitid == null ? null : fhrorgunitid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FCONTROLUNITID
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FCONTROLUNITID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public String getFcontrolunitid() {
        return fcontrolunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FCONTROLUNITID
     *
     * @param fcontrolunitid the value for T_HR_PERSONCONTACTMETHOD.FCONTROLUNITID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFcontrolunitid(String fcontrolunitid) {
        this.fcontrolunitid = fcontrolunitid == null ? null : fcontrolunitid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FHJADDRESS
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FHJADDRESS
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFhjaddress() {
        return fhjaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FHJADDRESS
     *
     * @param fhjaddress the value for T_HR_PERSONCONTACTMETHOD.FHJADDRESS
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFhjaddress(Object fhjaddress) {
        this.fhjaddress = fhjaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FIDCARDADDRESS
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FIDCARDADDRESS
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFidcardaddress() {
        return fidcardaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FIDCARDADDRESS
     *
     * @param fidcardaddress the value for T_HR_PERSONCONTACTMETHOD.FIDCARDADDRESS
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFidcardaddress(Object fidcardaddress) {
        this.fidcardaddress = fidcardaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FBACKUPEMAIL
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FBACKUPEMAIL
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFbackupemail() {
        return fbackupemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FBACKUPEMAIL
     *
     * @param fbackupemail the value for T_HR_PERSONCONTACTMETHOD.FBACKUPEMAIL
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFbackupemail(Object fbackupemail) {
        this.fbackupemail = fbackupemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FBACKUPMOBILE
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FBACKUPMOBILE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFbackupmobile() {
        return fbackupmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FBACKUPMOBILE
     *
     * @param fbackupmobile the value for T_HR_PERSONCONTACTMETHOD.FBACKUPMOBILE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFbackupmobile(Object fbackupmobile) {
        this.fbackupmobile = fbackupmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FREGRESIDENCEID
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FREGRESIDENCEID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFregresidenceid() {
        return fregresidenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FREGRESIDENCEID
     *
     * @param fregresidenceid the value for T_HR_PERSONCONTACTMETHOD.FREGRESIDENCEID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFregresidenceid(Object fregresidenceid) {
        this.fregresidenceid = fregresidenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FHUKOUKINGID
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FHUKOUKINGID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public String getFhukoukingid() {
        return fhukoukingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FHUKOUKINGID
     *
     * @param fhukoukingid the value for T_HR_PERSONCONTACTMETHOD.FHUKOUKINGID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFhukoukingid(String fhukoukingid) {
        this.fhukoukingid = fhukoukingid == null ? null : fhukoukingid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FMSN
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FMSN
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFmsn() {
        return fmsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FMSN
     *
     * @param fmsn the value for T_HR_PERSONCONTACTMETHOD.FMSN
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFmsn(Object fmsn) {
        this.fmsn = fmsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FQQ
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FQQ
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFqq() {
        return fqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FQQ
     *
     * @param fqq the value for T_HR_PERSONCONTACTMETHOD.FQQ
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFqq(Object fqq) {
        this.fqq = fqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FBACKUPOFFICEPHONE
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FBACKUPOFFICEPHONE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFbackupofficephone() {
        return fbackupofficephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FBACKUPOFFICEPHONE
     *
     * @param fbackupofficephone the value for T_HR_PERSONCONTACTMETHOD.FBACKUPOFFICEPHONE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFbackupofficephone(Object fbackupofficephone) {
        this.fbackupofficephone = fbackupofficephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FBACKUPHOMEPHONE
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FBACKUPHOMEPHONE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFbackuphomephone() {
        return fbackuphomephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FBACKUPHOMEPHONE
     *
     * @param fbackuphomephone the value for T_HR_PERSONCONTACTMETHOD.FBACKUPHOMEPHONE
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFbackuphomephone(Object fbackuphomephone) {
        this.fbackuphomephone = fbackuphomephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY1
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY1
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public String getFzdy1() {
        return fzdy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY1
     *
     * @param fzdy1 the value for T_HR_PERSONCONTACTMETHOD.FZDY1
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy1(String fzdy1) {
        this.fzdy1 = fzdy1 == null ? null : fzdy1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY2
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY2
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public String getFzdy2() {
        return fzdy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY2
     *
     * @param fzdy2 the value for T_HR_PERSONCONTACTMETHOD.FZDY2
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy2(String fzdy2) {
        this.fzdy2 = fzdy2 == null ? null : fzdy2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY3
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY3
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public String getFzdy3() {
        return fzdy3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY3
     *
     * @param fzdy3 the value for T_HR_PERSONCONTACTMETHOD.FZDY3
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy3(String fzdy3) {
        this.fzdy3 = fzdy3 == null ? null : fzdy3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY4
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY4
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public String getFzdy4() {
        return fzdy4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY4
     *
     * @param fzdy4 the value for T_HR_PERSONCONTACTMETHOD.FZDY4
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy4(String fzdy4) {
        this.fzdy4 = fzdy4 == null ? null : fzdy4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY5
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY5
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public String getFzdy5() {
        return fzdy5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY5
     *
     * @param fzdy5 the value for T_HR_PERSONCONTACTMETHOD.FZDY5
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy5(String fzdy5) {
        this.fzdy5 = fzdy5 == null ? null : fzdy5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY6
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY6
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public String getFzdy6() {
        return fzdy6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY6
     *
     * @param fzdy6 the value for T_HR_PERSONCONTACTMETHOD.FZDY6
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy6(String fzdy6) {
        this.fzdy6 = fzdy6 == null ? null : fzdy6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY7
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY7
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public String getFzdy7() {
        return fzdy7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY7
     *
     * @param fzdy7 the value for T_HR_PERSONCONTACTMETHOD.FZDY7
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy7(String fzdy7) {
        this.fzdy7 = fzdy7 == null ? null : fzdy7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY8
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY8
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public String getFzdy8() {
        return fzdy8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY8
     *
     * @param fzdy8 the value for T_HR_PERSONCONTACTMETHOD.FZDY8
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy8(String fzdy8) {
        this.fzdy8 = fzdy8 == null ? null : fzdy8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY9
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY9
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Date getFzdy9() {
        return fzdy9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY9
     *
     * @param fzdy9 the value for T_HR_PERSONCONTACTMETHOD.FZDY9
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy9(Date fzdy9) {
        this.fzdy9 = fzdy9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY10
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY10
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Date getFzdy10() {
        return fzdy10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY10
     *
     * @param fzdy10 the value for T_HR_PERSONCONTACTMETHOD.FZDY10
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy10(Date fzdy10) {
        this.fzdy10 = fzdy10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY11
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY11
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Date getFzdy11() {
        return fzdy11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY11
     *
     * @param fzdy11 the value for T_HR_PERSONCONTACTMETHOD.FZDY11
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy11(Date fzdy11) {
        this.fzdy11 = fzdy11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY12
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY12
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Date getFzdy12() {
        return fzdy12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY12
     *
     * @param fzdy12 the value for T_HR_PERSONCONTACTMETHOD.FZDY12
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy12(Date fzdy12) {
        this.fzdy12 = fzdy12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY13
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY13
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Date getFzdy13() {
        return fzdy13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY13
     *
     * @param fzdy13 the value for T_HR_PERSONCONTACTMETHOD.FZDY13
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy13(Date fzdy13) {
        this.fzdy13 = fzdy13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY14
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY14
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Date getFzdy14() {
        return fzdy14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY14
     *
     * @param fzdy14 the value for T_HR_PERSONCONTACTMETHOD.FZDY14
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy14(Date fzdy14) {
        this.fzdy14 = fzdy14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY15
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY15
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFzdy15() {
        return fzdy15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY15
     *
     * @param fzdy15 the value for T_HR_PERSONCONTACTMETHOD.FZDY15
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy15(Object fzdy15) {
        this.fzdy15 = fzdy15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY16
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY16
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFzdy16() {
        return fzdy16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY16
     *
     * @param fzdy16 the value for T_HR_PERSONCONTACTMETHOD.FZDY16
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy16(Object fzdy16) {
        this.fzdy16 = fzdy16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY17
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY17
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFzdy17() {
        return fzdy17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY17
     *
     * @param fzdy17 the value for T_HR_PERSONCONTACTMETHOD.FZDY17
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy17(Object fzdy17) {
        this.fzdy17 = fzdy17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY18
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY18
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public BigDecimal getFzdy18() {
        return fzdy18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY18
     *
     * @param fzdy18 the value for T_HR_PERSONCONTACTMETHOD.FZDY18
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy18(BigDecimal fzdy18) {
        this.fzdy18 = fzdy18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY19
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY19
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public BigDecimal getFzdy19() {
        return fzdy19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY19
     *
     * @param fzdy19 the value for T_HR_PERSONCONTACTMETHOD.FZDY19
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy19(BigDecimal fzdy19) {
        this.fzdy19 = fzdy19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY20
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY20
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Long getFzdy20() {
        return fzdy20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY20
     *
     * @param fzdy20 the value for T_HR_PERSONCONTACTMETHOD.FZDY20
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy20(Long fzdy20) {
        this.fzdy20 = fzdy20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY21
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY21
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Long getFzdy21() {
        return fzdy21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY21
     *
     * @param fzdy21 the value for T_HR_PERSONCONTACTMETHOD.FZDY21
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy21(Long fzdy21) {
        this.fzdy21 = fzdy21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY23
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY23
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFzdy23() {
        return fzdy23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY23
     *
     * @param fzdy23 the value for T_HR_PERSONCONTACTMETHOD.FZDY23
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy23(Object fzdy23) {
        this.fzdy23 = fzdy23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY24
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY24
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFzdy24() {
        return fzdy24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY24
     *
     * @param fzdy24 the value for T_HR_PERSONCONTACTMETHOD.FZDY24
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy24(Object fzdy24) {
        this.fzdy24 = fzdy24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY25
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY25
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFzdy25() {
        return fzdy25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY25
     *
     * @param fzdy25 the value for T_HR_PERSONCONTACTMETHOD.FZDY25
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy25(Object fzdy25) {
        this.fzdy25 = fzdy25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY26
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY26
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Long getFzdy26() {
        return fzdy26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY26
     *
     * @param fzdy26 the value for T_HR_PERSONCONTACTMETHOD.FZDY26
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy26(Long fzdy26) {
        this.fzdy26 = fzdy26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY22
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.FZDY22
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getFzdy22() {
        return fzdy22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.FZDY22
     *
     * @param fzdy22 the value for T_HR_PERSONCONTACTMETHOD.FZDY22
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setFzdy22(Object fzdy22) {
        this.fzdy22 = fzdy22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.CFMAIL
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.CFMAIL
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getCfmail() {
        return cfmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.CFMAIL
     *
     * @param cfmail the value for T_HR_PERSONCONTACTMETHOD.CFMAIL
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setCfmail(Object cfmail) {
        this.cfmail = cfmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.CFPRIMAIL
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.CFPRIMAIL
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getCfprimail() {
        return cfprimail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.CFPRIMAIL
     *
     * @param cfprimail the value for T_HR_PERSONCONTACTMETHOD.CFPRIMAIL
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setCfprimail(Object cfprimail) {
        this.cfprimail = cfprimail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.CFHJPOST
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.CFHJPOST
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getCfhjpost() {
        return cfhjpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.CFHJPOST
     *
     * @param cfhjpost the value for T_HR_PERSONCONTACTMETHOD.CFHJPOST
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setCfhjpost(Object cfhjpost) {
        this.cfhjpost = cfhjpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.CFNADDRESS
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.CFNADDRESS
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getCfnaddress() {
        return cfnaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.CFNADDRESS
     *
     * @param cfnaddress the value for T_HR_PERSONCONTACTMETHOD.CFNADDRESS
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setCfnaddress(Object cfnaddress) {
        this.cfnaddress = cfnaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.CFNADDRESSPOST
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.CFNADDRESSPOST
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public Object getCfnaddresspost() {
        return cfnaddresspost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.CFNADDRESSPOST
     *
     * @param cfnaddresspost the value for T_HR_PERSONCONTACTMETHOD.CFNADDRESSPOST
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setCfnaddresspost(Object cfnaddresspost) {
        this.cfnaddresspost = cfnaddresspost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HR_PERSONCONTACTMETHOD.CFHUKOULEIXINGID
     *
     * @return the value of T_HR_PERSONCONTACTMETHOD.CFHUKOULEIXINGID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public String getCfhukouleixingid() {
        return cfhukouleixingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HR_PERSONCONTACTMETHOD.CFHUKOULEIXINGID
     *
     * @param cfhukouleixingid the value for T_HR_PERSONCONTACTMETHOD.CFHUKOULEIXINGID
     *
     * @mbggenerated Mon Mar 18 18:34:14 CST 2013
     */
    public void setCfhukouleixingid(String cfhukouleixingid) {
        this.cfhukouleixingid = cfhukouleixingid == null ? null : cfhukouleixingid.trim();
    }
}