package com.creditease.eas.warn.bean;

import java.util.Date;

public class SendWay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SENDWAY.ID
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SENDWAY.WAYCODE
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String waycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SENDWAY.WAYNAME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String wayname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SENDWAY.CREATIME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private Date creatime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SENDWAY.EXT1
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SENDWAY.EXT2
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SENDWAY.EXT3
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SENDWAY.EXT4
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SENDWAY.EXT5
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SENDWAY.ID
     *
     * @return the value of T_SENDWAY.ID
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SENDWAY.ID
     *
     * @param id the value for T_SENDWAY.ID
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SENDWAY.WAYCODE
     *
     * @return the value of T_SENDWAY.WAYCODE
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getWaycode() {
        return waycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SENDWAY.WAYCODE
     *
     * @param waycode the value for T_SENDWAY.WAYCODE
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setWaycode(String waycode) {
        this.waycode = waycode == null ? null : waycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SENDWAY.WAYNAME
     *
     * @return the value of T_SENDWAY.WAYNAME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getWayname() {
        return wayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SENDWAY.WAYNAME
     *
     * @param wayname the value for T_SENDWAY.WAYNAME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setWayname(String wayname) {
        this.wayname = wayname == null ? null : wayname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SENDWAY.CREATIME
     *
     * @return the value of T_SENDWAY.CREATIME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public Date getCreatime() {
        return creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SENDWAY.CREATIME
     *
     * @param creatime the value for T_SENDWAY.CREATIME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setCreatime(Date creatime) {
        this.creatime = creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SENDWAY.EXT1
     *
     * @return the value of T_SENDWAY.EXT1
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SENDWAY.EXT1
     *
     * @param ext1 the value for T_SENDWAY.EXT1
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SENDWAY.EXT2
     *
     * @return the value of T_SENDWAY.EXT2
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SENDWAY.EXT2
     *
     * @param ext2 the value for T_SENDWAY.EXT2
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SENDWAY.EXT3
     *
     * @return the value of T_SENDWAY.EXT3
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SENDWAY.EXT3
     *
     * @param ext3 the value for T_SENDWAY.EXT3
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SENDWAY.EXT4
     *
     * @return the value of T_SENDWAY.EXT4
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt4() {
        return ext4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SENDWAY.EXT4
     *
     * @param ext4 the value for T_SENDWAY.EXT4
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt4(String ext4) {
        this.ext4 = ext4 == null ? null : ext4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SENDWAY.EXT5
     *
     * @return the value of T_SENDWAY.EXT5
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt5() {
        return ext5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SENDWAY.EXT5
     *
     * @param ext5 the value for T_SENDWAY.EXT5
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt5(String ext5) {
        this.ext5 = ext5 == null ? null : ext5.trim();
    }
}