package com.creditease.eas.warn.bean;

public class Variables {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VARIABLES.ID
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VARIABLES.CODESNAME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String codesname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VARIABLES.VARINAME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String variname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VARIABLES.ID
     *
     * @return the value of T_VARIABLES.ID
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VARIABLES.ID
     *
     * @param id the value for T_VARIABLES.ID
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VARIABLES.CODESNAME
     *
     * @return the value of T_VARIABLES.CODESNAME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getCodesname() {
        return codesname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VARIABLES.CODESNAME
     *
     * @param codesname the value for T_VARIABLES.CODESNAME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setCodesname(String codesname) {
        this.codesname = codesname == null ? null : codesname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VARIABLES.VARINAME
     *
     * @return the value of T_VARIABLES.VARINAME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getVariname() {
        return variname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VARIABLES.VARINAME
     *
     * @param variname the value for T_VARIABLES.VARINAME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setVariname(String variname) {
        this.variname = variname == null ? null : variname.trim();
    }
}