package com.creditease.eas.warn.bean;

import java.util.Date;

public class WaringDetailView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.ID
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.TYPENAME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String typename;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.TYPEID
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.WAYNAME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String wayname;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.THEME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String theme;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.SENDTIME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private Date sendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.CELL
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String cell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.DEPARTID
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String departid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.DEPARTNAME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String departname;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.BIRTHDAY
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.ENTERDATE
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private Date enterdate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.POSTID
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String postid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.POSTNAME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String postname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.RECEIVERIDS
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String receiverids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.RECEIVER
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EMAIL
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.COPYIDS
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String copyids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.COPYPERSON
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String copyperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.CREATIME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private Date creatime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.CELLCONTENT
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String cellcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.CONTENTADDRESS
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String contentaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.ISSEND
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private Short issend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.SENDCOUNT
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private Short sendcount;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.FILENAME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String filename;

    private Short typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.WAYID
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private Short wayid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT1
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT2
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT3
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT4
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT5
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT6
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT7
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT8
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT9
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT10
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT11
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT12
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT13
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT14
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT15
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT16
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT17
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT18
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT19
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_WARING_DETAIL.EXT20
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    private String ext20;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.ID
     *
     * @return the value of V_WARING_DETAIL.ID
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.ID
     *
     * @param id the value for V_WARING_DETAIL.ID
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.TYPEID
     *
     * @return the value of V_WARING_DETAIL.TYPEID
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public Short getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.TYPEID
     *
     * @param typeid the value for V_WARING_DETAIL.TYPEID
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setTypeid(Short typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.WAYID
     *
     * @return the value of V_WARING_DETAIL.WAYID
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public Short getWayid() {
        return wayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.WAYID
     *
     * @param wayid the value for V_WARING_DETAIL.WAYID
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setWayid(Short wayid) {
        this.wayid = wayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.SENDTIME
     *
     * @return the value of V_WARING_DETAIL.SENDTIME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.SENDTIME
     *
     * @param sendtime the value for V_WARING_DETAIL.SENDTIME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.CELL
     *
     * @return the value of V_WARING_DETAIL.CELL
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getCell() {
        return cell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.CELL
     *
     * @param cell the value for V_WARING_DETAIL.CELL
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setCell(String cell) {
        this.cell = cell == null ? null : cell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.BIRTHDAY
     *
     * @return the value of V_WARING_DETAIL.BIRTHDAY
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.BIRTHDAY
     *
     * @param birthday the value for V_WARING_DETAIL.BIRTHDAY
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.ENTERDATE
     *
     * @return the value of V_WARING_DETAIL.ENTERDATE
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public Date getEnterdate() {
        return enterdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.ENTERDATE
     *
     * @param enterdate the value for V_WARING_DETAIL.ENTERDATE
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setEnterdate(Date enterdate) {
        this.enterdate = enterdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.DEPARTID
     *
     * @return the value of V_WARING_DETAIL.DEPARTID
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getDepartid() {
        return departid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.DEPARTID
     *
     * @param departid the value for V_WARING_DETAIL.DEPARTID
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setDepartid(String departid) {
        this.departid = departid == null ? null : departid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.DEPARTNAME
     *
     * @return the value of V_WARING_DETAIL.DEPARTNAME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getDepartname() {
        return departname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.DEPARTNAME
     *
     * @param departname the value for V_WARING_DETAIL.DEPARTNAME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setDepartname(String departname) {
        this.departname = departname == null ? null : departname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.POSTID
     *
     * @return the value of V_WARING_DETAIL.POSTID
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.POSTID
     *
     * @param postid the value for V_WARING_DETAIL.POSTID
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setPostid(String postid) {
        this.postid = postid == null ? null : postid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.POSTNAME
     *
     * @return the value of V_WARING_DETAIL.POSTNAME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getPostname() {
        return postname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.POSTNAME
     *
     * @param postname the value for V_WARING_DETAIL.POSTNAME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setPostname(String postname) {
        this.postname = postname == null ? null : postname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.RECEIVERIDS
     *
     * @return the value of V_WARING_DETAIL.RECEIVERIDS
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getReceiverids() {
        return receiverids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.RECEIVERIDS
     *
     * @param receiverids the value for V_WARING_DETAIL.RECEIVERIDS
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setReceiverids(String receiverids) {
        this.receiverids = receiverids == null ? null : receiverids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.RECEIVER
     *
     * @return the value of V_WARING_DETAIL.RECEIVER
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.RECEIVER
     *
     * @param receiver the value for V_WARING_DETAIL.RECEIVER
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EMAIL
     *
     * @return the value of V_WARING_DETAIL.EMAIL
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EMAIL
     *
     * @param email the value for V_WARING_DETAIL.EMAIL
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.COPYIDS
     *
     * @return the value of V_WARING_DETAIL.COPYIDS
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getCopyids() {
        return copyids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.COPYIDS
     *
     * @param copyids the value for V_WARING_DETAIL.COPYIDS
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setCopyids(String copyids) {
        this.copyids = copyids == null ? null : copyids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.COPYPERSON
     *
     * @return the value of V_WARING_DETAIL.COPYPERSON
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getCopyperson() {
        return copyperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.COPYPERSON
     *
     * @param copyperson the value for V_WARING_DETAIL.COPYPERSON
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setCopyperson(String copyperson) {
        this.copyperson = copyperson == null ? null : copyperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.THEME
     *
     * @return the value of V_WARING_DETAIL.THEME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.THEME
     *
     * @param theme the value for V_WARING_DETAIL.THEME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.CONTENTADDRESS
     *
     * @return the value of V_WARING_DETAIL.CONTENTADDRESS
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getContentaddress() {
        return contentaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.CONTENTADDRESS
     *
     * @param contentaddress the value for V_WARING_DETAIL.CONTENTADDRESS
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setContentaddress(String contentaddress) {
        this.contentaddress = contentaddress == null ? null : contentaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.ISSEND
     *
     * @return the value of V_WARING_DETAIL.ISSEND
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public Short getIssend() {
        return issend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.ISSEND
     *
     * @param issend the value for V_WARING_DETAIL.ISSEND
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setIssend(Short issend) {
        this.issend = issend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.SENDCOUNT
     *
     * @return the value of V_WARING_DETAIL.SENDCOUNT
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public Short getSendcount() {
        return sendcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.SENDCOUNT
     *
     * @param sendcount the value for V_WARING_DETAIL.SENDCOUNT
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setSendcount(Short sendcount) {
        this.sendcount = sendcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.CREATIME
     *
     * @return the value of V_WARING_DETAIL.CREATIME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public Date getCreatime() {
        return creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.CREATIME
     *
     * @param creatime the value for V_WARING_DETAIL.CREATIME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setCreatime(Date creatime) {
        this.creatime = creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT1
     *
     * @return the value of V_WARING_DETAIL.EXT1
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT1
     *
     * @param ext1 the value for V_WARING_DETAIL.EXT1
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT2
     *
     * @return the value of V_WARING_DETAIL.EXT2
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT2
     *
     * @param ext2 the value for V_WARING_DETAIL.EXT2
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT3
     *
     * @return the value of V_WARING_DETAIL.EXT3
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT3
     *
     * @param ext3 the value for V_WARING_DETAIL.EXT3
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT4
     *
     * @return the value of V_WARING_DETAIL.EXT4
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt4() {
        return ext4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT4
     *
     * @param ext4 the value for V_WARING_DETAIL.EXT4
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt4(String ext4) {
        this.ext4 = ext4 == null ? null : ext4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT5
     *
     * @return the value of V_WARING_DETAIL.EXT5
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt5() {
        return ext5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT5
     *
     * @param ext5 the value for V_WARING_DETAIL.EXT5
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt5(String ext5) {
        this.ext5 = ext5 == null ? null : ext5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT6
     *
     * @return the value of V_WARING_DETAIL.EXT6
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt6() {
        return ext6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT6
     *
     * @param ext6 the value for V_WARING_DETAIL.EXT6
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt6(String ext6) {
        this.ext6 = ext6 == null ? null : ext6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT7
     *
     * @return the value of V_WARING_DETAIL.EXT7
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt7() {
        return ext7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT7
     *
     * @param ext7 the value for V_WARING_DETAIL.EXT7
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt7(String ext7) {
        this.ext7 = ext7 == null ? null : ext7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT8
     *
     * @return the value of V_WARING_DETAIL.EXT8
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt8() {
        return ext8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT8
     *
     * @param ext8 the value for V_WARING_DETAIL.EXT8
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt8(String ext8) {
        this.ext8 = ext8 == null ? null : ext8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT9
     *
     * @return the value of V_WARING_DETAIL.EXT9
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt9() {
        return ext9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT9
     *
     * @param ext9 the value for V_WARING_DETAIL.EXT9
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt9(String ext9) {
        this.ext9 = ext9 == null ? null : ext9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT10
     *
     * @return the value of V_WARING_DETAIL.EXT10
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt10() {
        return ext10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT10
     *
     * @param ext10 the value for V_WARING_DETAIL.EXT10
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt10(String ext10) {
        this.ext10 = ext10 == null ? null : ext10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT11
     *
     * @return the value of V_WARING_DETAIL.EXT11
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt11() {
        return ext11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT11
     *
     * @param ext11 the value for V_WARING_DETAIL.EXT11
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt11(String ext11) {
        this.ext11 = ext11 == null ? null : ext11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT12
     *
     * @return the value of V_WARING_DETAIL.EXT12
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt12() {
        return ext12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT12
     *
     * @param ext12 the value for V_WARING_DETAIL.EXT12
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt12(String ext12) {
        this.ext12 = ext12 == null ? null : ext12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT13
     *
     * @return the value of V_WARING_DETAIL.EXT13
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt13() {
        return ext13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT13
     *
     * @param ext13 the value for V_WARING_DETAIL.EXT13
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt13(String ext13) {
        this.ext13 = ext13 == null ? null : ext13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT14
     *
     * @return the value of V_WARING_DETAIL.EXT14
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt14() {
        return ext14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT14
     *
     * @param ext14 the value for V_WARING_DETAIL.EXT14
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt14(String ext14) {
        this.ext14 = ext14 == null ? null : ext14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT15
     *
     * @return the value of V_WARING_DETAIL.EXT15
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt15() {
        return ext15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT15
     *
     * @param ext15 the value for V_WARING_DETAIL.EXT15
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt15(String ext15) {
        this.ext15 = ext15 == null ? null : ext15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT16
     *
     * @return the value of V_WARING_DETAIL.EXT16
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt16() {
        return ext16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT16
     *
     * @param ext16 the value for V_WARING_DETAIL.EXT16
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt16(String ext16) {
        this.ext16 = ext16 == null ? null : ext16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT17
     *
     * @return the value of V_WARING_DETAIL.EXT17
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt17() {
        return ext17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT17
     *
     * @param ext17 the value for V_WARING_DETAIL.EXT17
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt17(String ext17) {
        this.ext17 = ext17 == null ? null : ext17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT18
     *
     * @return the value of V_WARING_DETAIL.EXT18
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt18() {
        return ext18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT18
     *
     * @param ext18 the value for V_WARING_DETAIL.EXT18
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt18(String ext18) {
        this.ext18 = ext18 == null ? null : ext18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT19
     *
     * @return the value of V_WARING_DETAIL.EXT19
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt19() {
        return ext19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT19
     *
     * @param ext19 the value for V_WARING_DETAIL.EXT19
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt19(String ext19) {
        this.ext19 = ext19 == null ? null : ext19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.EXT20
     *
     * @return the value of V_WARING_DETAIL.EXT20
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getExt20() {
        return ext20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.EXT20
     *
     * @param ext20 the value for V_WARING_DETAIL.EXT20
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setExt20(String ext20) {
        this.ext20 = ext20 == null ? null : ext20.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.CELLCONTENT
     *
     * @return the value of V_WARING_DETAIL.CELLCONTENT
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getCellcontent() {
        return cellcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.CELLCONTENT
     *
     * @param cellcontent the value for V_WARING_DETAIL.CELLCONTENT
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setCellcontent(String cellcontent) {
        this.cellcontent = cellcontent == null ? null : cellcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.FILENAME
     *
     * @return the value of V_WARING_DETAIL.FILENAME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.FILENAME
     *
     * @param filename the value for V_WARING_DETAIL.FILENAME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.WAYNAME
     *
     * @return the value of V_WARING_DETAIL.WAYNAME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getWayname() {
        return wayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.WAYNAME
     *
     * @param wayname the value for V_WARING_DETAIL.WAYNAME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setWayname(String wayname) {
        this.wayname = wayname == null ? null : wayname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_WARING_DETAIL.TYPENAME
     *
     * @return the value of V_WARING_DETAIL.TYPENAME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_WARING_DETAIL.TYPENAME
     *
     * @param typename the value for V_WARING_DETAIL.TYPENAME
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }
}