package com.creditease.eas.warn.bean;

import java.util.Date;

public class WaringType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WARINGTYPE.ID
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WARINGTYPE.TYPECODE
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String typecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WARINGTYPE.TYPENAME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WARINGTYPE.CREATIME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private Date creatime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WARINGTYPE.EXT1
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WARINGTYPE.EXT2
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WARINGTYPE.EXT3
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WARINGTYPE.EXT4
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WARINGTYPE.EXT5
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    private String ext5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WARINGTYPE.ID
     *
     * @return the value of T_WARINGTYPE.ID
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WARINGTYPE.ID
     *
     * @param id the value for T_WARINGTYPE.ID
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WARINGTYPE.TYPECODE
     *
     * @return the value of T_WARINGTYPE.TYPECODE
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WARINGTYPE.TYPECODE
     *
     * @param typecode the value for T_WARINGTYPE.TYPECODE
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setTypecode(String typecode) {
        this.typecode = typecode == null ? null : typecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WARINGTYPE.TYPENAME
     *
     * @return the value of T_WARINGTYPE.TYPENAME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WARINGTYPE.TYPENAME
     *
     * @param typename the value for T_WARINGTYPE.TYPENAME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WARINGTYPE.CREATIME
     *
     * @return the value of T_WARINGTYPE.CREATIME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public Date getCreatime() {
        return creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WARINGTYPE.CREATIME
     *
     * @param creatime the value for T_WARINGTYPE.CREATIME
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setCreatime(Date creatime) {
        this.creatime = creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WARINGTYPE.EXT1
     *
     * @return the value of T_WARINGTYPE.EXT1
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WARINGTYPE.EXT1
     *
     * @param ext1 the value for T_WARINGTYPE.EXT1
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WARINGTYPE.EXT2
     *
     * @return the value of T_WARINGTYPE.EXT2
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WARINGTYPE.EXT2
     *
     * @param ext2 the value for T_WARINGTYPE.EXT2
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WARINGTYPE.EXT3
     *
     * @return the value of T_WARINGTYPE.EXT3
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WARINGTYPE.EXT3
     *
     * @param ext3 the value for T_WARINGTYPE.EXT3
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WARINGTYPE.EXT4
     *
     * @return the value of T_WARINGTYPE.EXT4
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt4() {
        return ext4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WARINGTYPE.EXT4
     *
     * @param ext4 the value for T_WARINGTYPE.EXT4
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt4(String ext4) {
        this.ext4 = ext4 == null ? null : ext4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WARINGTYPE.EXT5
     *
     * @return the value of T_WARINGTYPE.EXT5
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public String getExt5() {
        return ext5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WARINGTYPE.EXT5
     *
     * @param ext5 the value for T_WARINGTYPE.EXT5
     *
     * @mbggenerated Mon Dec 24 14:34:43 CST 2012
     */
    public void setExt5(String ext5) {
        this.ext5 = ext5 == null ? null : ext5.trim();
    }
}