package com.creditease.eas.adminipurc.vo;

import java.util.Date;
/***
 * 行政采购合同预警对应的合同信息
 * @Title:AdminContractInfo.java
 * @Package com.creditease.eas.adminipurc.bean
 * created at 2014-5-25 下午04:32:40 by ygq
 * @author ygq
 * @version 1.0
 */
public class AdminContractInfoVo {
	private Long  fid;
	//合同编号
    private String fnumber;
	//组织名称
    private String forgname;
    //城市
    private String fcity;
    //末级成本中心
    private String flastcostcenter;
    //办公室坐落地点
    private String fofficeaddr;
    //合同类别
    private Integer fcontracttypeid;
    //供应商名称
    private String fsuppliername;
    //合同额
    private String fcontractamount;
    //开始日期
    private String fbegindate;
    //结束日期
    private String fenddate;
    //无特殊情况自动续签
    private String fisrenewal;
    //合同期限
    private Long fdurtime;
    //月费用
    private String fmonthcost;
    //打印设备押金
    private String fprintdeposit;
    //付款方式
    private Integer fpaytypeid;

    //合同状态：1.在用2.删除
    private String fdeletestatus;
    //合同到期跟进:1.生效 2.已续签、3.续签申请中、4.不续签
    private Integer fcontractstatus;
    //备注
    private String fremark;
    /**创建人**/
    private Long fcreator;
    /**创建时间**/
    private Date fcreatetime;
    /**最后更新人姓名**/
    private Long flastupdater;
    /**最后更新时间**/
    private Date flastupdatetime;
    public Long getFid() {
		return fid;
	}

	public void setFid(Long fid) {
		this.fid = fid;
	}
    public String getForgname() {
		return forgname;
	}

	public void setForgname(String forgname) {
		this.forgname = forgname;
	}

	public String getFcity() {
		return fcity;
	}

	public void setFcity(String fcity) {
		this.fcity = fcity;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMINI_CONTRACTINFO.FLASTCOSTCENTER
     *
     * @return the value of T_ADMINI_CONTRACTINFO.FLASTCOSTCENTER
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public String getFlastcostcenter() {
        return flastcostcenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMINI_CONTRACTINFO.FLASTCOSTCENTER
     *
     * @param flastcostcenter the value for T_ADMINI_CONTRACTINFO.FLASTCOSTCENTER
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public void setFlastcostcenter(String flastcostcenter) {
        this.flastcostcenter = flastcostcenter == null ? null : flastcostcenter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMINI_CONTRACTINFO.FOFFICEADDR
     *
     * @return the value of T_ADMINI_CONTRACTINFO.FOFFICEADDR
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public String getFofficeaddr() {
        return fofficeaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMINI_CONTRACTINFO.FOFFICEADDR
     *
     * @param fofficeaddr the value for T_ADMINI_CONTRACTINFO.FOFFICEADDR
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public void setFofficeaddr(String fofficeaddr) {
        this.fofficeaddr = fofficeaddr == null ? null : fofficeaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMINI_CONTRACTINFO.FNUMBER
     *
     * @return the value of T_ADMINI_CONTRACTINFO.FNUMBER
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public String getFnumber() {
        return fnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMINI_CONTRACTINFO.FNUMBER
     *
     * @param fnumber the value for T_ADMINI_CONTRACTINFO.FNUMBER
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public void setFnumber(String fnumber) {
        this.fnumber = fnumber == null ? null : fnumber.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMINI_CONTRACTINFO.FSUPPLIERNAME
     *
     * @return the value of T_ADMINI_CONTRACTINFO.FSUPPLIERNAME
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public String getFsuppliername() {
        return fsuppliername;
    }
	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMINI_CONTRACTINFO.FSUPPLIERNAME
     *
     * @param fsuppliername the value for T_ADMINI_CONTRACTINFO.FSUPPLIERNAME
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public void setFsuppliername(String fsuppliername) {
        this.fsuppliername = fsuppliername == null ? null : fsuppliername.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMINI_CONTRACTINFO.FBEGINDATE
     *
     * @return the value of T_ADMINI_CONTRACTINFO.FBEGINDATE
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public String getFbegindate() {
        return fbegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMINI_CONTRACTINFO.FBEGINDATE
     *
     * @param fbegindate the value for T_ADMINI_CONTRACTINFO.FBEGINDATE
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public void setFbegindate(String fbegindate) {
        this.fbegindate = fbegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMINI_CONTRACTINFO.FENDDATE
     *
     * @return the value of T_ADMINI_CONTRACTINFO.FENDDATE
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public String getFenddate() {
        return fenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMINI_CONTRACTINFO.FENDDATE
     *
     * @param fenddate the value for T_ADMINI_CONTRACTINFO.FENDDATE
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public void setFenddate(String fenddate) {
        this.fenddate = fenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMINI_CONTRACTINFO.FISRENEWAL
     *
     * @return the value of T_ADMINI_CONTRACTINFO.FISRENEWAL
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public String getFisrenewal() {
        return fisrenewal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMINI_CONTRACTINFO.FISRENEWAL
     *
     * @param fisrenewal the value for T_ADMINI_CONTRACTINFO.FISRENEWAL
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public void setFisrenewal(String fisrenewal) {
        this.fisrenewal = fisrenewal == null ? null : fisrenewal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMINI_CONTRACTINFO.FDURTIME
     *
     * @return the value of T_ADMINI_CONTRACTINFO.FDURTIME
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public Long getFdurtime() {
        return fdurtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMINI_CONTRACTINFO.FDURTIME
     *
     * @param fdurtime the value for T_ADMINI_CONTRACTINFO.FDURTIME
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public void setFdurtime(Long fdurtime) {
        this.fdurtime = fdurtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMINI_CONTRACTINFO.FMONTHCOST
     *
     * @return the value of T_ADMINI_CONTRACTINFO.FMONTHCOST
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public String getFmonthcost() {
        return fmonthcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMINI_CONTRACTINFO.FMONTHCOST
     *
     * @param fmonthcost the value for T_ADMINI_CONTRACTINFO.FMONTHCOST
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public void setFmonthcost(String fmonthcost) {
        this.fmonthcost = fmonthcost == null ? null : fmonthcost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMINI_CONTRACTINFO.FPRINTDEPOSIT
     *
     * @return the value of T_ADMINI_CONTRACTINFO.FPRINTDEPOSIT
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public String getFprintdeposit() {
        return fprintdeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMINI_CONTRACTINFO.FPRINTDEPOSIT
     *
     * @param fprintdeposit the value for T_ADMINI_CONTRACTINFO.FPRINTDEPOSIT
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public void setFprintdeposit(String fprintdeposit) {
        this.fprintdeposit = fprintdeposit == null ? null : fprintdeposit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMINI_CONTRACTINFO.FDELETESTATUS
     *
     * @return the value of T_ADMINI_CONTRACTINFO.FDELETESTATUS
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public String getFdeletestatus() {
        return fdeletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMINI_CONTRACTINFO.FDELETESTATUS
     *
     * @param fdeletestatus the value for T_ADMINI_CONTRACTINFO.FDELETESTATUS
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public void setFdeletestatus(String fdeletestatus) {
        this.fdeletestatus = fdeletestatus == null ? null : fdeletestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMINI_CONTRACTINFO.FCONTRACTSTATUS
     *
     * @return the value of T_ADMINI_CONTRACTINFO.FCONTRACTSTATUS
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public Integer getFcontractstatus() {
        return fcontractstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMINI_CONTRACTINFO.FCONTRACTSTATUS
     *
     * @param fcontractstatus the value for T_ADMINI_CONTRACTINFO.FCONTRACTSTATUS
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public void setFcontractstatus(Integer fcontractstatus) {
        this.fcontractstatus = fcontractstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMINI_CONTRACTINFO.FREMARK
     *
     * @return the value of T_ADMINI_CONTRACTINFO.FREMARK
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public String getFremark() {
        return fremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMINI_CONTRACTINFO.FREMARK
     *
     * @param fremark the value for T_ADMINI_CONTRACTINFO.FREMARK
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public void setFremark(String fremark) {
        this.fremark = fremark == null ? null : fremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMINI_CONTRACTINFO.FCREATOR
     *
     * @return the value of T_ADMINI_CONTRACTINFO.FCREATOR
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public Long getFcreator() {
        return fcreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMINI_CONTRACTINFO.FCREATOR
     *
     * @param fcreator the value for T_ADMINI_CONTRACTINFO.FCREATOR
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public void setFcreator(Long fcreator) {
        this.fcreator = fcreator;
    }

    public Date getFcreatetime() {
		return fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMINI_CONTRACTINFO.FLASTUPDATER
     *
     * @return the value of T_ADMINI_CONTRACTINFO.FLASTUPDATER
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public Long getFlastupdater() {
        return flastupdater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMINI_CONTRACTINFO.FLASTUPDATER
     *
     * @param flastupdater the value for T_ADMINI_CONTRACTINFO.FLASTUPDATER
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public void setFlastupdater(Long flastupdater) {
        this.flastupdater = flastupdater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMINI_CONTRACTINFO.FLASTUPDATETIME
     *
     * @return the value of T_ADMINI_CONTRACTINFO.FLASTUPDATETIME
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public Date getFlastupdatetime() {
        return flastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMINI_CONTRACTINFO.FLASTUPDATETIME
     *
     * @param flastupdatetime the value for T_ADMINI_CONTRACTINFO.FLASTUPDATETIME
     *
     * @mbggenerated Sun May 25 16:30:10 CST 2014
     */
    public void setFlastupdatetime(Date flastupdatetime) {
        this.flastupdatetime = flastupdatetime;
    }

    public Integer getFcontracttypeid() {
		return fcontracttypeid;
	}

	public void setFcontracttypeid(Integer fcontracttypeid) {
		this.fcontracttypeid = fcontracttypeid;
	}

	public String getFcontractamount() {
		return fcontractamount;
	}

	public void setFcontractamount(String fcontractamount) {
		this.fcontractamount = fcontractamount;
	}

	public Integer getFpaytypeid() {
		return fpaytypeid;
	}

	public void setFpaytypeid(Integer fpaytypeid) {
		this.fpaytypeid = fpaytypeid;
	}
}