package com.creditease.eas.warn.kingdee.dao;

import java.util.List;
import java.util.Map;

import com.creditease.eas.util.BaseDAO;
import com.creditease.eas.warn.bean.PersonData;
import com.creditease.eas.warn.bean.personContactMethod;


public interface PersonDataMapper extends BaseDAO<PersonData, Integer>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERSONDATA
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
	
	public List personDataList();
	
	public List waringQueryList(List<String> numlist);
	
    int deleteByPrimaryKey(Long dtid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERSONDATA
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
   // int insert(PersonData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERSONDATA
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    int insertSelective(PersonData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERSONDATA
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
   // PersonData selectByPrimaryKey(Long dtid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERSONDATA
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    int updateByPrimaryKeySelective(PersonData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERSONDATA
     *
     * @mbggenerated Mon Dec 24 17:09:03 CST 2012
     */
    int updateByPrimaryKey(PersonData record);
    
    
    public List<Map<String,Object>> selectPersonInfoByPositionId(String strid);
    /**
     * 被注释掉的这两个方法是最初需求时，需要查询经理以上和经理以下人员的代码
     * 现在需求已经改成不需要区分经理以上及经理以下了，所以这两个方法已经过时了
     * 并且在现行的方法中不再被引用
     * @return
     */
    @Deprecated
    public List<Map<String,Object>> getYearOfWork();
    @Deprecated
    public List<Map<String,Object>> getYearOfWork2();
//    
    public Map<String,Object> getCeo();
    
    public Map<String,Object> getHr();
    
    public Map<String,Object> selectResponsePersonInfo(String strid);
    
    public List<Map<String,Object>> sendImage(List<String> numlist);

    public List<Map<String,Object>> getALLNoEmail();
    
    public int getCounts();
    
    public void updateByPrimaryKeySelective(personContactMethod record);
    
    public List<Map<String,Object>> getALLEmail();
    
    
    public List<Map<String,Object>> getALLEmailOfCount();
    
    public List<Map<String,Object>> getNoEmail();
    
    public int findEmail(String email);
    
    public Integer findMaxByEmail(String str);
    
    public List<Map<String,Object>> getNoPcm(); 
    /**
     * 
     * 描述：经理以下人员入职信息
     * 2013-4-2 下午03:30:37 by xjw
     * @version
     * @return
     */
    public List<Map<String,Object>> getWorkPerson(List<String> numlist);
    
    public Map<String,Object> getPersonByFid(String strid);
    
    public void trimName(); 
    
    public void trimMail(); 
}