package com.creditease.eas.warn.dao;
import java.util.List;
import java.util.Map;

import com.creditease.eas.util.BaseDAO;
import com.creditease.eas.warn.bean.BlackListInfo;
import com.creditease.eas.warn.bean.Processmode;
import com.creditease.eas.warn.bean.WaringType;

public interface BlackListInfoMapper extends BaseDAO<BlackListInfo, Integer>{
	
	//获取所有黑名单信息
	public Map<String,Object> blackList();
	
	public Processmode getProcessmode(Integer mid);
	
	public WaringType getWaringType(Integer wid);
	
	public List<Processmode> modeList();
	
	public List<WaringType> warntypeList();
	
	 int deleteByPrimaryKey(Integer pid);

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table t_blacklistinfo
	     *
	     * @mbggenerated Mon Jul 01 19:37:04 CST 2013
	     */
	    int insertBlackListInfo(BlackListInfo record);

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table t_blacklistinfo
	     *
	     * @mbggenerated Mon Jul 01 19:37:04 CST 2013
	     */
	    int insertSelective(BlackListInfo record);

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table t_blacklistinfo
	     *
	     * @mbggenerated Mon Jul 01 19:37:04 CST 2013
	     */
	    BlackListInfo selectByPrimaryKey(Integer pid);
	    
	    BlackListInfo selectByFnumber(Map map);

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table t_blacklistinfo
	     *
	     * @mbggenerated Mon Jul 01 19:37:04 CST 2013
	     */
	    int updateByPrimaryKeySelective(BlackListInfo record);

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table t_blacklistinfo
	     *
	     * @mbggenerated Mon Jul 01 19:37:04 CST 2013
	     */
	    int updateByPrimaryKey(BlackListInfo record);
}
