package com.creditease.eas.warn.dao;

import com.creditease.eas.util.BaseDAO;
import com.creditease.eas.warn.bean.ConfigInfo;


public interface ConfigInfoMapper extends BaseDAO<ConfigInfo, Integer>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ConfigInfo
     *
     * @mbggenerated Mon Dec 24 10:15:10 CST 2012
     */
    int deleteByPrimaryKey(Integer id);

    public int maxId();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ConfigInfo
     *
     * @mbggenerated Mon Dec 24 10:15:10 CST 2012
     */
    int insertConfigInfo(ConfigInfo record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ConfigInfo
     *
     * @mbggenerated Mon Dec 24 10:15:10 CST 2012
     */
    int insertSelective(ConfigInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ConfigInfo
     *
     * @mbggenerated Mon Dec 24 10:15:10 CST 2012
     */
    ConfigInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ConfigInfo
     *
     * @mbggenerated Mon Dec 24 10:15:10 CST 2012
     */
    int updateByPrimaryKeySelective(ConfigInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ConfigInfo
     *
     * @mbggenerated Mon Dec 24 10:15:10 CST 2012
     */
    int updateByPrimaryKey(ConfigInfo record);
    
    ConfigInfo selectByIsuse(Integer isuse);
}