package com.creditease.eas.warn.dao;

import java.util.List;
import java.util.Map;

import com.creditease.eas.warn.bean.SendWay;


public interface SendWayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SENDWAY
     *
     * @mbggenerated Mon Dec 24 10:15:10 CST 2012
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SENDWAY
     *
     * @mbggenerated Mon Dec 24 10:15:10 CST 2012
     */
    int insert(SendWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SENDWAY
     *
     * @mbggenerated Mon Dec 24 10:15:10 CST 2012
     */
    int insertSelective(SendWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SENDWAY
     *
     * @mbggenerated Mon Dec 24 10:15:10 CST 2012
     */
    SendWay selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SENDWAY
     *
     * @mbggenerated Mon Dec 24 10:15:10 CST 2012
     */
    int updateByPrimaryKeySelective(SendWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SENDWAY
     *
     * @mbggenerated Mon Dec 24 10:15:10 CST 2012
     */
    int updateByPrimaryKey(SendWay record);
    /**
     * 
     * 描述：查询所有的发送方式
     * 2012-12-28 下午05:00:52 by ygq
     * @version
     * @return
     */
    public List<Map<String,Object>> selectAllSendWays();
}