package com.creditease.eas.warn.dao;

import com.creditease.eas.util.BaseDAO;
import com.creditease.eas.warn.bean.Variables;


public interface VariablesMapper extends BaseDAO<Variables, Integer>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VARIABLES
     *
     * @mbggenerated Mon Dec 24 10:15:10 CST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VARIABLES
     *
     * @mbggenerated Mon Dec 24 10:15:10 CST 2012
     */
    int insertVariables(Variables record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VARIABLES
     *
     * @mbggenerated Mon Dec 24 10:15:10 CST 2012
     */
    int insertSelective(Variables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VARIABLES
     *
     * @mbggenerated Mon Dec 24 10:15:10 CST 2012
     */
    Variables selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VARIABLES
     *
     * @mbggenerated Mon Dec 24 10:15:10 CST 2012
     */
    int updateByPrimaryKeySelective(Variables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VARIABLES
     *
     * @mbggenerated Mon Dec 24 10:15:10 CST 2012
     */
    int updateByPrimaryKey(Variables record);
}