package com.creditease.eas.warn.dao;

import java.util.List;
import java.util.Map;

import com.creditease.eas.util.BaseDAO;
import com.creditease.eas.warn.bean.WaringDetail;
import com.creditease.eas.warn.bean.WaringDetailView;


public interface WaringDetailViewMapper extends BaseDAO<WaringDetail, Integer> {
	/**
	 * 
	 * 描述：查询带参数的数据集
	 * 2013-1-1 下午04:27:01 by ygq
	 * @version
	 * @param params
	 * @return
	 */
	public List<WaringDetailView> queryByParams(Map params);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_WARING_DETAIL
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    int insert(WaringDetailView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_WARING_DETAIL
     *
     * @mbggenerated Mon Dec 31 10:18:58 CST 2012
     */
    int insertSelective(WaringDetailView record);
    
    int updateByPrimaryKeySelective(WaringDetail record);
}