package empwebservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import com.creditease.eas.util.consts.AddressConfig;
/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * IEmpChangeSuceedServiceService service = new IEmpChangeSuceedServiceService();
 * EmpService portType = service.getEmpServicePort();
 * portType.queryEmpInfoChangeFromHRToSMPAndOA(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "IEmpChangeSuceedServiceService", targetNamespace = "empWebService", wsdlLocation = AddressConfig.EMPWSDLLOCATION)
public class IEmpChangeSuceedServiceService extends Service {

	private final static URL IEMPCHANGESUCEEDSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(empwebservice.IEmpChangeSuceedServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = empwebservice.IEmpChangeSuceedServiceService.class
					.getResource(".");
			url = new URL(
					baseUrl,
					AddressConfig.EMPWSDLLOCATION);
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://10.105.18.140:9002/empChangeSuceed/services/empchangeSuceedService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		IEMPCHANGESUCEEDSERVICESERVICE_WSDL_LOCATION = url;
	}

	public IEmpChangeSuceedServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public IEmpChangeSuceedServiceService() {
		super(IEMPCHANGESUCEEDSERVICESERVICE_WSDL_LOCATION, new QName(
				"empWebService", "IEmpChangeSuceedServiceService"));
	}

	/**
	 * 
	 * @return returns EmpService
	 */
	@WebEndpoint(name = "empServicePort")
	public EmpService getEmpServicePort() {
		return super.getPort(new QName("empWebService", "empServicePort"),
				EmpService.class);
	}

}
