package com.creditease.eas.hr.dao;

import com.creditease.eas.hr.bean.Wsorganization;

public interface WsorganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_WS_ORGANIZATION
     *
     * @mbggenerated Mon Feb 25 16:34:01 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_WS_ORGANIZATION
     *
     * @mbggenerated Mon Feb 25 16:34:01 CST 2013
     */
    int insert(Wsorganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_WS_ORGANIZATION
     *
     * @mbggenerated Mon Feb 25 16:34:01 CST 2013
     */
    int insertSelective(Wsorganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_WS_ORGANIZATION
     *
     * @mbggenerated Mon Feb 25 16:34:01 CST 2013
     */
    Wsorganization selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_WS_ORGANIZATION
     *
     * @mbggenerated Mon Feb 25 16:34:01 CST 2013
     */
    int updateByPrimaryKeySelective(Wsorganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_WS_ORGANIZATION
     *
     * @mbggenerated Mon Feb 25 16:34:01 CST 2013
     */
    int updateByPrimaryKey(Wsorganization record);
}