package com.creditease.eas.hr.dao;

import com.creditease.eas.hr.bean.Wspositioninfo;

public interface WspositioninfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_WS_POSITIONINFO
     *
     * @mbggenerated Mon Feb 25 16:34:01 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_WS_POSITIONINFO
     *
     * @mbggenerated Mon Feb 25 16:34:01 CST 2013
     */
    int insert(Wspositioninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_WS_POSITIONINFO
     *
     * @mbggenerated Mon Feb 25 16:34:01 CST 2013
     */
    int insertSelective(Wspositioninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_WS_POSITIONINFO
     *
     * @mbggenerated Mon Feb 25 16:34:01 CST 2013
     */
    Wspositioninfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_WS_POSITIONINFO
     *
     * @mbggenerated Mon Feb 25 16:34:01 CST 2013
     */
    int updateByPrimaryKeySelective(Wspositioninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_WS_POSITIONINFO
     *
     * @mbggenerated Mon Feb 25 16:34:01 CST 2013
     */
    int updateByPrimaryKey(Wspositioninfo record);
}