package com.creditease.eas.compliance.bean;

import java.util.Date;

import com.creditease.eas.util.MethodDesAnnotation;
/***
 * 案件信息表
 * @Complain.java
 * created at 2013-10-8 下午02:07:29 by ygq
 * 
 * @author ygq({@link authorEmail})
 * @version $Revision$</br>
 * update: $Date$
 */
public class Complain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private Integer fid;
    /**
     * 案件编号
     */
    private String fnumber;
    public String getFnumber() {
		return fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FCOMPLAINANT
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
	@MethodDesAnnotation(description="投诉人")
    private String fcomplainanter;

    public String getFcomplainanter() {
		return fcomplainanter;
	}

	public void setFcomplainanter(String fcomplainanter) {
		this.fcomplainanter = fcomplainanter;
	}

	/**
     *是客户本人
     */
	@MethodDesAnnotation(description="客户本人")
    private String fiscustomer;
    /**
   * 身份证号
   */
	@MethodDesAnnotation(description="客户身份证号")
    private String fidcard;
    /**
     * 客户姓名
     */
    @MethodDesAnnotation(description="客户姓名")
      private String fcusName;
      //负责人
      private String fresponsibleName;
      //负责人邮箱
      private String fresponsibleEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FMOBILE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fmobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FOFFICEPHONE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fofficephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FQQ
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fqq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FEMAIL
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String femail;

    /**
     * 客户来源
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private Integer fcussourceid;

    /**
     * 服务类型
     */
    private Integer fservicetypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FINANCIALPLAN
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String financialplan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FSTARTORENDTIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fstartorendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FSALESMANNAME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fsalesmanname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FSERVICENAME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fservicename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FFIRSTTRIAL
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String ffirsttrial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FLASTTRIAL
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String flasttrial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FDENIEDLOANS
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fdeniedloans;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FCONTRACTNUMBER
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fcontractnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FCONTRACTTIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private Date fcontracttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FLOANTIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private Date floantime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FLOANBREAD
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String floanbread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FREIMBSTRATTIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String freimbstrattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FREIMBENDTIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String freimbendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FAMOUNT
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String famount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FDEADLINE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fdeadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FISVIOLATE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fisviolate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FVIOLATEDAYS
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private Integer fviolatedays;

    /**
     * 投诉渠道
     * 
     */
    private Integer fcompchannelid;

    /***
     * 投诉时间
     */
    private Date fcomptime;

    /**
     * 是否有书面证据 1.有，0：无
     */
    private String fisevidence;

    /**
     * 证据类型
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private Integer fevidencetypeid;

    //是否是内部员工	1.是0.否
    private String fisinner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FBUSPORTID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private Integer fbusportid;
    /**
     * 案件具体描述
     */
    private String fdetaildescrip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FCREATEUSERID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private Integer fcreateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FCREATETIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private Date fcreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FUPDATEUSERID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private Integer fupdateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FLASTUPDATETIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private Date flastupdatetime;
    /**
     * 中间的状态变量
     * 1.普通
     * 2.暂存：暂存的案件信息不处理
     */
    private Integer ftempstatus;//暂存状态(1:普通,2:暂存）
    private Integer fcusstatusid;//客户状态
    private String fremarks;//备注
    private String fcusrelation;//与客户关系
    private String fcompcontactinfo;//与投诉人的联系方式
    private String fcomplainidcard;//投诉人的身份证号
    private Integer findex;//案件序号
    private String fselfEmailRemark;//投诉渠道个人邮箱备注
    private String fisevidenceRemarks;//证据类型备注
    private String finicasetypeRemark;//案件初步分类选择其他的时候的备注
	private String fviolateCountHistory;//历史违约次数
	public Integer getFindex() {
		return findex;
	}

	public void setFindex(Integer findex) {
		this.findex = findex;
	}

	public String getFcusrelation() {
		return fcusrelation;
	}

	public void setFcusrelation(String fcusrelation) {
		this.fcusrelation = fcusrelation;
	}

	public String getFcompcontactinfo() {
		return fcompcontactinfo;
	}

	public void setFcompcontactinfo(String fcompcontactinfo) {
		this.fcompcontactinfo = fcompcontactinfo;
	}

	public String getFcomplainidcard() {
		return fcomplainidcard;
	}

	public void setFcomplainidcard(String fcomplainidcard) {
		this.fcomplainidcard = fcomplainidcard;
	}
	public Integer getFcusstatusid() {
		return fcusstatusid;
	}

	public void setFcusstatusid(Integer fcusstatusid) {
		this.fcusstatusid = fcusstatusid;
	}

	public String getFremarks() {
		return fremarks;
	}

	public void setFremarks(String fremarks) {
		this.fremarks = fremarks;
	}

	public Integer getFtempstatus() {
		return ftempstatus;
	}

	public void setFtempstatus(Integer ftempstatus) {
		this.ftempstatus = ftempstatus;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FEXT1
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FEXT2
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FEXT3
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fext3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FEXT4
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fext4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FEXT5
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fext5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FEXT6
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fext6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FEXT7
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fext7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FEXT8
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fext8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FEXT9
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fext9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPLAIN.FEXT10
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fext10;
    
    
    private String fnewtypemark;
    
    /**
     * 是否收费
     */
    private String isCharge;
    
    private String SRCode;

    public String getIsCharge() {
		return isCharge;
	}
   
	public void setIsCharge(String isCharge) {
		this.isCharge = isCharge;
	}
	 
    public String getSRCode() {
		return SRCode;
	}

	public void setSRCode(String sRCode) {
		SRCode = sRCode;
	}

	/**
     * 风险评估
     */
    private String riskLevel;
    
    

	public String getRiskLevel() {
		return riskLevel;
	}

	public void setRiskLevel(String riskLevel) {
		this.riskLevel = riskLevel;
	}

	public String getFinicasetypeRemark() {
		return finicasetypeRemark;
	}

	public void setFinicasetypeRemark(String finicasetypeRemark) {
		this.finicasetypeRemark = finicasetypeRemark;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FID
     *
     * @return the value of T_COM_COMPLAIN.FID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FID
     *
     * @param fid the value for T_COM_COMPLAIN.FID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

	public String getFiscustomer() {
        return fiscustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FISCUSTOMER
     *
     * @param fiscustomer the value for T_COM_COMPLAIN.FISCUSTOMER
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFiscustomer(String fiscustomer) {
        this.fiscustomer = fiscustomer == null ? null : fiscustomer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FIDCARD
     *
     * @return the value of T_COM_COMPLAIN.FIDCARD
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFidcard() {
        return fidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FIDCARD
     *
     * @param fidcard the value for T_COM_COMPLAIN.FIDCARD
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFidcard(String fidcard) {
        this.fidcard = fidcard == null ? null : fidcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FMOBILE
     *
     * @return the value of T_COM_COMPLAIN.FMOBILE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFmobile() {
        return fmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FMOBILE
     *
     * @param fmobile the value for T_COM_COMPLAIN.FMOBILE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFmobile(String fmobile) {
        this.fmobile = fmobile == null ? null : fmobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FOFFICEPHONE
     *
     * @return the value of T_COM_COMPLAIN.FOFFICEPHONE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFofficephone() {
        return fofficephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FOFFICEPHONE
     *
     * @param fofficephone the value for T_COM_COMPLAIN.FOFFICEPHONE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFofficephone(String fofficephone) {
        this.fofficephone = fofficephone == null ? null : fofficephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FQQ
     *
     * @return the value of T_COM_COMPLAIN.FQQ
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFqq() {
        return fqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FQQ
     *
     * @param fqq the value for T_COM_COMPLAIN.FQQ
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFqq(String fqq) {
        this.fqq = fqq == null ? null : fqq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FEMAIL
     *
     * @return the value of T_COM_COMPLAIN.FEMAIL
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFemail() {
        return femail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FEMAIL
     *
     * @param femail the value for T_COM_COMPLAIN.FEMAIL
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFemail(String femail) {
        this.femail = femail == null ? null : femail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FCUSSOURCEID
     *
     * @return the value of T_COM_COMPLAIN.FCUSSOURCEID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public Integer getFcussourceid() {
        return fcussourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FCUSSOURCEID
     *
     * @param fcussourceid the value for T_COM_COMPLAIN.FCUSSOURCEID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFcussourceid(Integer fcussourceid) {
        this.fcussourceid = fcussourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FSERVICETYPEID
     *
     * @return the value of T_COM_COMPLAIN.FSERVICETYPEID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public Integer getFservicetypeid() {
        return fservicetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FSERVICETYPEID
     *
     * @param fservicetypeid the value for T_COM_COMPLAIN.FSERVICETYPEID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFservicetypeid(Integer fservicetypeid) {
        this.fservicetypeid = fservicetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FINANCIALPLAN
     *
     * @return the value of T_COM_COMPLAIN.FINANCIALPLAN
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFinancialplan() {
        return financialplan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FINANCIALPLAN
     *
     * @param financialplan the value for T_COM_COMPLAIN.FINANCIALPLAN
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFinancialplan(String financialplan) {
        this.financialplan = financialplan == null ? null : financialplan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FSTARTORENDTIME
     *
     * @return the value of T_COM_COMPLAIN.FSTARTORENDTIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFstartorendtime() {
        return fstartorendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FSTARTORENDTIME
     *
     * @param fstartorendtime the value for T_COM_COMPLAIN.FSTARTORENDTIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFstartorendtime(String fstartorendtime) {
        this.fstartorendtime = fstartorendtime == null ? null : fstartorendtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FSALESMANNAME
     *
     * @return the value of T_COM_COMPLAIN.FSALESMANNAME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFsalesmanname() {
        return fsalesmanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FSALESMANNAME
     *
     * @param fsalesmanname the value for T_COM_COMPLAIN.FSALESMANNAME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFsalesmanname(String fsalesmanname) {
        this.fsalesmanname = fsalesmanname == null ? null : fsalesmanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FSERVICENAME
     *
     * @return the value of T_COM_COMPLAIN.FSERVICENAME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFservicename() {
        return fservicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FSERVICENAME
     *
     * @param fservicename the value for T_COM_COMPLAIN.FSERVICENAME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFservicename(String fservicename) {
        this.fservicename = fservicename == null ? null : fservicename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FFIRSTTRIAL
     *
     * @return the value of T_COM_COMPLAIN.FFIRSTTRIAL
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFfirsttrial() {
        return ffirsttrial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FFIRSTTRIAL
     *
     * @param ffirsttrial the value for T_COM_COMPLAIN.FFIRSTTRIAL
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFfirsttrial(String ffirsttrial) {
        this.ffirsttrial = ffirsttrial == null ? null : ffirsttrial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FLASTTRIAL
     *
     * @return the value of T_COM_COMPLAIN.FLASTTRIAL
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFlasttrial() {
        return flasttrial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FLASTTRIAL
     *
     * @param flasttrial the value for T_COM_COMPLAIN.FLASTTRIAL
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFlasttrial(String flasttrial) {
        this.flasttrial = flasttrial == null ? null : flasttrial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FDENIEDLOANS
     *
     * @return the value of T_COM_COMPLAIN.FDENIEDLOANS
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFdeniedloans() {
        return fdeniedloans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FDENIEDLOANS
     *
     * @param fdeniedloans the value for T_COM_COMPLAIN.FDENIEDLOANS
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFdeniedloans(String fdeniedloans) {
        this.fdeniedloans = fdeniedloans == null ? null : fdeniedloans.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FCONTRACTNUMBER
     *
     * @return the value of T_COM_COMPLAIN.FCONTRACTNUMBER
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFcontractnumber() {
        return fcontractnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FCONTRACTNUMBER
     *
     * @param fcontractnumber the value for T_COM_COMPLAIN.FCONTRACTNUMBER
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFcontractnumber(String fcontractnumber) {
        this.fcontractnumber = fcontractnumber == null ? null : fcontractnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FCONTRACTTIME
     *
     * @return the value of T_COM_COMPLAIN.FCONTRACTTIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public Date getFcontracttime() {
        return fcontracttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FCONTRACTTIME
     *
     * @param fcontracttime the value for T_COM_COMPLAIN.FCONTRACTTIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFcontracttime(Date fcontracttime) {
        this.fcontracttime = fcontracttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FLOANTIME
     *
     * @return the value of T_COM_COMPLAIN.FLOANTIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public Date getFloantime() {
        return floantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FLOANTIME
     *
     * @param floantime the value for T_COM_COMPLAIN.FLOANTIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFloantime(Date floantime) {
        this.floantime = floantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FLOANBREAD
     *
     * @return the value of T_COM_COMPLAIN.FLOANBREAD
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFloanbread() {
        return floanbread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FLOANBREAD
     *
     * @param floanbread the value for T_COM_COMPLAIN.FLOANBREAD
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFloanbread(String floanbread) {
        this.floanbread = floanbread == null ? null : floanbread.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FREIMBSTRATTIME
     *
     * @return the value of T_COM_COMPLAIN.FREIMBSTRATTIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFreimbstrattime() {
        return freimbstrattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FREIMBSTRATTIME
     *
     * @param freimbstrattime the value for T_COM_COMPLAIN.FREIMBSTRATTIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFreimbstrattime(String freimbstrattime) {
        this.freimbstrattime = freimbstrattime == null ? null : freimbstrattime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FREIMBENDTIME
     *
     * @return the value of T_COM_COMPLAIN.FREIMBENDTIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFreimbendtime() {
        return freimbendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FREIMBENDTIME
     *
     * @param freimbendtime the value for T_COM_COMPLAIN.FREIMBENDTIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFreimbendtime(String freimbendtime) {
        this.freimbendtime = freimbendtime == null ? null : freimbendtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FAMOUNT
     *
     * @return the value of T_COM_COMPLAIN.FAMOUNT
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFamount() {
        return famount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FAMOUNT
     *
     * @param famount the value for T_COM_COMPLAIN.FAMOUNT
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFamount(String famount) {
        this.famount = famount == null ? null : famount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FDEADLINE
     *
     * @return the value of T_COM_COMPLAIN.FDEADLINE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFdeadline() {
        return fdeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FDEADLINE
     *
     * @param fdeadline the value for T_COM_COMPLAIN.FDEADLINE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFdeadline(String fdeadline) {
        this.fdeadline = fdeadline == null ? null : fdeadline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FISVIOLATE
     *
     * @return the value of T_COM_COMPLAIN.FISVIOLATE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFisviolate() {
        return fisviolate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FISVIOLATE
     *
     * @param fisviolate the value for T_COM_COMPLAIN.FISVIOLATE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFisviolate(String fisviolate) {
        this.fisviolate = fisviolate == null ? null : fisviolate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FVIOLATEDAYS
     *
     * @return the value of T_COM_COMPLAIN.FVIOLATEDAYS
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public Integer getFviolatedays() {
        return fviolatedays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FVIOLATEDAYS
     *
     * @param fviolatedays the value for T_COM_COMPLAIN.FVIOLATEDAYS
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFviolatedays(Integer fviolatedays) {
        this.fviolatedays = fviolatedays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FCOMPCHANNELID
     *
     * @return the value of T_COM_COMPLAIN.FCOMPCHANNELID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public Integer getFcompchannelid() {
        return fcompchannelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FCOMPCHANNELID
     *
     * @param fcompchannelid the value for T_COM_COMPLAIN.FCOMPCHANNELID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFcompchannelid(Integer fcompchannelid) {
        this.fcompchannelid = fcompchannelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FCOMPTIME
     *
     * @return the value of T_COM_COMPLAIN.FCOMPTIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public Date getFcomptime() {
        return fcomptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FCOMPTIME
     *
     * @param fcomptime the value for T_COM_COMPLAIN.FCOMPTIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFcomptime(Date fcomptime) {
        this.fcomptime = fcomptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FISEVIDENCE
     *
     * @return the value of T_COM_COMPLAIN.FISEVIDENCE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFisevidence() {
        return fisevidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FISEVIDENCE
     *
     * @param fisevidence the value for T_COM_COMPLAIN.FISEVIDENCE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFisevidence(String fisevidence) {
        this.fisevidence = fisevidence == null ? null : fisevidence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FEVIDENCETYPEID
     *
     * @return the value of T_COM_COMPLAIN.FEVIDENCETYPEID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public Integer getFevidencetypeid() {
        return fevidencetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FEVIDENCETYPEID
     *
     * @param fevidencetypeid the value for T_COM_COMPLAIN.FEVIDENCETYPEID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFevidencetypeid(Integer fevidencetypeid) {
        this.fevidencetypeid = fevidencetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FISINNER
     *
     * @return the value of T_COM_COMPLAIN.FISINNER
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFisinner() {
        return fisinner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FISINNER
     *
     * @param fisinner the value for T_COM_COMPLAIN.FISINNER
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFisinner(String fisinner) {
        this.fisinner = fisinner == null ? null : fisinner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FBUSPORTID
     *
     * @return the value of T_COM_COMPLAIN.FBUSPORTID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public Integer getFbusportid() {
        return fbusportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FBUSPORTID
     *
     * @param fbusportid the value for T_COM_COMPLAIN.FBUSPORTID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFbusportid(Integer fbusportid) {
        this.fbusportid = fbusportid;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FDETAILDESCRIP
     *
     * @return the value of T_COM_COMPLAIN.FDETAILDESCRIP
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFdetaildescrip() {
        return fdetaildescrip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FDETAILDESCRIP
     *
     * @param fdetaildescrip the value for T_COM_COMPLAIN.FDETAILDESCRIP
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFdetaildescrip(String fdetaildescrip) {
        this.fdetaildescrip = fdetaildescrip == null ? null : fdetaildescrip.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FCREATEUSERID
     *
     * @return the value of T_COM_COMPLAIN.FCREATEUSERID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public Integer getFcreateuserid() {
        return fcreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FCREATEUSERID
     *
     * @param fcreateuserid the value for T_COM_COMPLAIN.FCREATEUSERID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFcreateuserid(Integer fcreateuserid) {
        this.fcreateuserid = fcreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FCREATETIME
     *
     * @return the value of T_COM_COMPLAIN.FCREATETIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public Date getFcreatetime() {
        return fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FCREATETIME
     *
     * @param fcreatetime the value for T_COM_COMPLAIN.FCREATETIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFcreatetime(Date fcreatetime) {
        this.fcreatetime = fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FUPDATEUSERID
     *
     * @return the value of T_COM_COMPLAIN.FUPDATEUSERID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public Integer getFupdateuserid() {
        return fupdateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FUPDATEUSERID
     *
     * @param fupdateuserid the value for T_COM_COMPLAIN.FUPDATEUSERID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFupdateuserid(Integer fupdateuserid) {
        this.fupdateuserid = fupdateuserid;
    }
    public String getFisevidenceRemarks() {
		return fisevidenceRemarks;
	}

	public void setFisevidenceRemarks(String fisevidenceRemarks) {
		this.fisevidenceRemarks = fisevidenceRemarks;
	}
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FLASTUPDATETIME
     *
     * @return the value of T_COM_COMPLAIN.FLASTUPDATETIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public Date getFlastupdatetime() {
        return flastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FLASTUPDATETIME
     *
     * @param flastupdatetime the value for T_COM_COMPLAIN.FLASTUPDATETIME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFlastupdatetime(Date flastupdatetime) {
        this.flastupdatetime = flastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FEXT1
     *
     * @return the value of T_COM_COMPLAIN.FEXT1
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFext1() {
        return fext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FEXT1
     *
     * @param fext1 the value for T_COM_COMPLAIN.FEXT1
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFext1(String fext1) {
        this.fext1 = fext1 == null ? null : fext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FEXT2
     *
     * @return the value of T_COM_COMPLAIN.FEXT2
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFext2() {
        return fext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FEXT2
     *
     * @param fext2 the value for T_COM_COMPLAIN.FEXT2
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFext2(String fext2) {
        this.fext2 = fext2 == null ? null : fext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FEXT3
     *
     * @return the value of T_COM_COMPLAIN.FEXT3
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFext3() {
        return fext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FEXT3
     *
     * @param fext3 the value for T_COM_COMPLAIN.FEXT3
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFext3(String fext3) {
        this.fext3 = fext3 == null ? null : fext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FEXT4
     *
     * @return the value of T_COM_COMPLAIN.FEXT4
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFext4() {
        return fext4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FEXT4
     *
     * @param fext4 the value for T_COM_COMPLAIN.FEXT4
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFext4(String fext4) {
        this.fext4 = fext4 == null ? null : fext4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FEXT5
     *
     * @return the value of T_COM_COMPLAIN.FEXT5
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFext5() {
        return fext5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FEXT5
     *
     * @param fext5 the value for T_COM_COMPLAIN.FEXT5
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFext5(String fext5) {
        this.fext5 = fext5 == null ? null : fext5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FEXT6
     *
     * @return the value of T_COM_COMPLAIN.FEXT6
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFext6() {
        return fext6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FEXT6
     *
     * @param fext6 the value for T_COM_COMPLAIN.FEXT6
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFext6(String fext6) {
        this.fext6 = fext6 == null ? null : fext6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FEXT7
     *
     * @return the value of T_COM_COMPLAIN.FEXT7
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFext7() {
        return fext7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FEXT7
     *
     * @param fext7 the value for T_COM_COMPLAIN.FEXT7
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFext7(String fext7) {
        this.fext7 = fext7 == null ? null : fext7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FEXT8
     *
     * @return the value of T_COM_COMPLAIN.FEXT8
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFext8() {
        return fext8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FEXT8
     *
     * @param fext8 the value for T_COM_COMPLAIN.FEXT8
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFext8(String fext8) {
        this.fext8 = fext8 == null ? null : fext8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FEXT9
     *
     * @return the value of T_COM_COMPLAIN.FEXT9
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFext9() {
        return fext9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FEXT9
     *
     * @param fext9 the value for T_COM_COMPLAIN.FEXT9
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFext9(String fext9) {
        this.fext9 = fext9 == null ? null : fext9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPLAIN.FEXT10
     *
     * @return the value of T_COM_COMPLAIN.FEXT10
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFext10() {
        return fext10;
    }

    public String getFselfEmailRemark() {
		return fselfEmailRemark;
	}

	public void setFselfEmailRemark(String fselfEmailRemark) {
		this.fselfEmailRemark = fselfEmailRemark;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPLAIN.FEXT10
     *
     * @param fext10 the value for T_COM_COMPLAIN.FEXT10
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFext10(String fext10) {
        this.fext10 = fext10 == null ? null : fext10.trim();
    }

	public String getFcusName() {
		return fcusName;
	}

	public void setFcusName(String fcusName) {
		this.fcusName = fcusName;
	}

	public String getFresponsibleName() {
		return fresponsibleName;
	}

	public void setFresponsibleName(String fresponsibleName) {
		this.fresponsibleName = fresponsibleName;
	}

	public String getFresponsibleEmail() {
		return fresponsibleEmail;
	}

	public void setFresponsibleEmail(String fresponsibleEmail) {
		this.fresponsibleEmail = fresponsibleEmail;
	}
	 public String getFviolateCountHistory() {
			return fviolateCountHistory;
	}

	public void setFviolateCountHistory(String fviolateCountHistory) {
		this.fviolateCountHistory = fviolateCountHistory;
	}

	public String getFnewtypemark() {
		return fnewtypemark;
	}

	public void setFnewtypemark(String fnewtypemark) {
		this.fnewtypemark = fnewtypemark;
	}
	
	/**
	 * 进件编号
	 */
	private String caseComeIntoCode;
	
	/**
	 * 进件时间
	 */
	private String caseComeIntoDate;
	
	/**
	 * 案件来源ID
	 */
	private Integer casefrom;
	
	/**
	 * 案件来源
	 */
	private String casefromPlace;
	
	/**
	 * 销售人员
	 */
	private String salePerson;
	
	/**
	 * 上级领导
	 */
	private String superLeader;
	
	/**
	 * 间接领导
	 */
	private String indirectLeader;
	
	/**
	 * 营业部
	 */
	private String saleDepart;
	
	/**
	 * 客服姓名
	 */
	private String serviceName;
	
	
	public String getCaseComeIntoCode() {
		return caseComeIntoCode;
	}

	public void setCaseComeIntoCode(String caseComeIntoCode) {
		this.caseComeIntoCode = caseComeIntoCode;
	}

	public String getCaseComeIntoDate() {
		return caseComeIntoDate;
	}

	public void setCaseComeIntoDate(String caseComeIntoDate) {
		this.caseComeIntoDate = caseComeIntoDate;
	}

	public Integer getCasefrom() {
		return casefrom;
	}

	public void setCasefrom(Integer casefrom) {
		this.casefrom = casefrom;
	}

	public String getCasefromPlace() {
		return casefromPlace;
	}

	public void setCasefromPlace(String casefromPlace) {
		this.casefromPlace = casefromPlace;
	}

	public String getSalePerson() {
		return salePerson;
	}

	public void setSalePerson(String salePerson) {
		this.salePerson = salePerson;
	}

	public String getSuperLeader() {
		return superLeader;
	}

	public void setSuperLeader(String superLeader) {
		this.superLeader = superLeader;
	}

	public String getIndirectLeader() {
		return indirectLeader;
	}

	public void setIndirectLeader(String indirectLeader) {
		this.indirectLeader = indirectLeader;
	}

	public String getSaleDepart() {
		return saleDepart;
	}

	public void setSaleDepart(String saleDepart) {
		this.saleDepart = saleDepart;
	}

	public String getServiceName() {
		return serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

}