package com.creditease.eas.compliance.bean;

public class CompersonTemp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPERSONTEMP.FID
     *
     * @mbggenerated Sun Oct 20 16:52:14 CST 2013
     */
    private Long fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPERSONTEMP.FCOMPID
     *
     * @mbggenerated Sun Oct 20 16:52:14 CST 2013
     */
    private Long fcompid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_COMPERSONTEMP.FPERSONID
     *
     * @mbggenerated Sun Oct 20 16:52:14 CST 2013
     */
    private Long fpersonid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPERSONTEMP.FID
     *
     * @return the value of T_COM_COMPERSONTEMP.FID
     *
     * @mbggenerated Sun Oct 20 16:52:14 CST 2013
     */
    public Long getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPERSONTEMP.FID
     *
     * @param fid the value for T_COM_COMPERSONTEMP.FID
     *
     * @mbggenerated Sun Oct 20 16:52:14 CST 2013
     */
    public void setFid(Long fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPERSONTEMP.FCOMPID
     *
     * @return the value of T_COM_COMPERSONTEMP.FCOMPID
     *
     * @mbggenerated Sun Oct 20 16:52:14 CST 2013
     */
    public Long getFcompid() {
        return fcompid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPERSONTEMP.FCOMPID
     *
     * @param fcompid the value for T_COM_COMPERSONTEMP.FCOMPID
     *
     * @mbggenerated Sun Oct 20 16:52:14 CST 2013
     */
    public void setFcompid(Long fcompid) {
        this.fcompid = fcompid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_COMPERSONTEMP.FPERSONID
     *
     * @return the value of T_COM_COMPERSONTEMP.FPERSONID
     *
     * @mbggenerated Sun Oct 20 16:52:14 CST 2013
     */
    public Long getFpersonid() {
        return fpersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_COMPERSONTEMP.FPERSONID
     *
     * @param fpersonid the value for T_COM_COMPERSONTEMP.FPERSONID
     *
     * @mbggenerated Sun Oct 20 16:52:14 CST 2013
     */
    public void setFpersonid(Long fpersonid) {
        this.fpersonid = fpersonid;
    }
}