package com.creditease.eas.compliance.bean;

import java.util.Date;

public class DEPTINFO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FID
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private Long fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FDEPTNAME
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private String fdeptname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FCITYNAME
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private String fcityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FSALEDEPART
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private String fsaledepart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FEXT1
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private String fext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FEXT2
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private String fext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FEXT3
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private String fext3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FEXT4
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private String fext4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FEXT5
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private String fext5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FEXT6
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private String fext6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FEXT7
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private String fext7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FEXT8
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private String fext8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FEXT9
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private String fext9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FEXT10
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private String fext10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FCOMPLAINID
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private Long fcomplainid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FCREATEUSERID
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private Long fcreateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FCREATETIME
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private Date fcreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FUPDATEUSERID
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private Long fupdateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DEPTINFO.FLASTUPDATETIME
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    private Date flastupdatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FID
     *
     * @return the value of T_COM_DEPTINFO.FID
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public Long getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FID
     *
     * @param fid the value for T_COM_DEPTINFO.FID
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFid(Long fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FDEPTNAME
     *
     * @return the value of T_COM_DEPTINFO.FDEPTNAME
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public String getFdeptname() {
        return fdeptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FDEPTNAME
     *
     * @param fdeptname the value for T_COM_DEPTINFO.FDEPTNAME
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFdeptname(String fdeptname) {
        this.fdeptname = fdeptname == null ? null : fdeptname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FCITYNAME
     *
     * @return the value of T_COM_DEPTINFO.FCITYNAME
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public String getFcityname() {
        return fcityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FCITYNAME
     *
     * @param fcityname the value for T_COM_DEPTINFO.FCITYNAME
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFcityname(String fcityname) {
        this.fcityname = fcityname == null ? null : fcityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FSALEDEPART
     *
     * @return the value of T_COM_DEPTINFO.FSALEDEPART
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public String getFsaledepart() {
        return fsaledepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FSALEDEPART
     *
     * @param fsaledepart the value for T_COM_DEPTINFO.FSALEDEPART
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFsaledepart(String fsaledepart) {
        this.fsaledepart = fsaledepart == null ? null : fsaledepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FEXT1
     *
     * @return the value of T_COM_DEPTINFO.FEXT1
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public String getFext1() {
        return fext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FEXT1
     *
     * @param fext1 the value for T_COM_DEPTINFO.FEXT1
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFext1(String fext1) {
        this.fext1 = fext1 == null ? null : fext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FEXT2
     *
     * @return the value of T_COM_DEPTINFO.FEXT2
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public String getFext2() {
        return fext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FEXT2
     *
     * @param fext2 the value for T_COM_DEPTINFO.FEXT2
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFext2(String fext2) {
        this.fext2 = fext2 == null ? null : fext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FEXT3
     *
     * @return the value of T_COM_DEPTINFO.FEXT3
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public String getFext3() {
        return fext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FEXT3
     *
     * @param fext3 the value for T_COM_DEPTINFO.FEXT3
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFext3(String fext3) {
        this.fext3 = fext3 == null ? null : fext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FEXT4
     *
     * @return the value of T_COM_DEPTINFO.FEXT4
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public String getFext4() {
        return fext4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FEXT4
     *
     * @param fext4 the value for T_COM_DEPTINFO.FEXT4
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFext4(String fext4) {
        this.fext4 = fext4 == null ? null : fext4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FEXT5
     *
     * @return the value of T_COM_DEPTINFO.FEXT5
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public String getFext5() {
        return fext5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FEXT5
     *
     * @param fext5 the value for T_COM_DEPTINFO.FEXT5
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFext5(String fext5) {
        this.fext5 = fext5 == null ? null : fext5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FEXT6
     *
     * @return the value of T_COM_DEPTINFO.FEXT6
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public String getFext6() {
        return fext6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FEXT6
     *
     * @param fext6 the value for T_COM_DEPTINFO.FEXT6
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFext6(String fext6) {
        this.fext6 = fext6 == null ? null : fext6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FEXT7
     *
     * @return the value of T_COM_DEPTINFO.FEXT7
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public String getFext7() {
        return fext7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FEXT7
     *
     * @param fext7 the value for T_COM_DEPTINFO.FEXT7
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFext7(String fext7) {
        this.fext7 = fext7 == null ? null : fext7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FEXT8
     *
     * @return the value of T_COM_DEPTINFO.FEXT8
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public String getFext8() {
        return fext8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FEXT8
     *
     * @param fext8 the value for T_COM_DEPTINFO.FEXT8
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFext8(String fext8) {
        this.fext8 = fext8 == null ? null : fext8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FEXT9
     *
     * @return the value of T_COM_DEPTINFO.FEXT9
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public String getFext9() {
        return fext9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FEXT9
     *
     * @param fext9 the value for T_COM_DEPTINFO.FEXT9
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFext9(String fext9) {
        this.fext9 = fext9 == null ? null : fext9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FEXT10
     *
     * @return the value of T_COM_DEPTINFO.FEXT10
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public String getFext10() {
        return fext10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FEXT10
     *
     * @param fext10 the value for T_COM_DEPTINFO.FEXT10
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFext10(String fext10) {
        this.fext10 = fext10 == null ? null : fext10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FCOMPLAINID
     *
     * @return the value of T_COM_DEPTINFO.FCOMPLAINID
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public Long getFcomplainid() {
        return fcomplainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FCOMPLAINID
     *
     * @param fcomplainid the value for T_COM_DEPTINFO.FCOMPLAINID
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFcomplainid(Long fcomplainid) {
        this.fcomplainid = fcomplainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FCREATEUSERID
     *
     * @return the value of T_COM_DEPTINFO.FCREATEUSERID
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public Long getFcreateuserid() {
        return fcreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FCREATEUSERID
     *
     * @param fcreateuserid the value for T_COM_DEPTINFO.FCREATEUSERID
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFcreateuserid(Long fcreateuserid) {
        this.fcreateuserid = fcreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FCREATETIME
     *
     * @return the value of T_COM_DEPTINFO.FCREATETIME
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public Date getFcreatetime() {
        return fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FCREATETIME
     *
     * @param fcreatetime the value for T_COM_DEPTINFO.FCREATETIME
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFcreatetime(Date fcreatetime) {
        this.fcreatetime = fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FUPDATEUSERID
     *
     * @return the value of T_COM_DEPTINFO.FUPDATEUSERID
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public Long getFupdateuserid() {
        return fupdateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FUPDATEUSERID
     *
     * @param fupdateuserid the value for T_COM_DEPTINFO.FUPDATEUSERID
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFupdateuserid(Long fupdateuserid) {
        this.fupdateuserid = fupdateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DEPTINFO.FLASTUPDATETIME
     *
     * @return the value of T_COM_DEPTINFO.FLASTUPDATETIME
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public Date getFlastupdatetime() {
        return flastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DEPTINFO.FLASTUPDATETIME
     *
     * @param flastupdatetime the value for T_COM_DEPTINFO.FLASTUPDATETIME
     *
     * @mbggenerated Fri Nov 01 09:24:42 CST 2013
     */
    public void setFlastupdatetime(Date flastupdatetime) {
        this.flastupdatetime = flastupdatetime;
    }
}