package com.creditease.eas.compliance.bean;

public class Detailcasetype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DETAILCASETYPE.FID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private Long fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DETAILCASETYPE.FNAME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DETAILCASETYPE.FNUMBER
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_DETAILCASETYPE.FINICASETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private Long finicasetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DETAILCASETYPE.FID
     *
     * @return the value of T_COM_DETAILCASETYPE.FID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public Long getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DETAILCASETYPE.FID
     *
     * @param fid the value for T_COM_DETAILCASETYPE.FID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFid(Long fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DETAILCASETYPE.FNAME
     *
     * @return the value of T_COM_DETAILCASETYPE.FNAME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DETAILCASETYPE.FNAME
     *
     * @param fname the value for T_COM_DETAILCASETYPE.FNAME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DETAILCASETYPE.FNUMBER
     *
     * @return the value of T_COM_DETAILCASETYPE.FNUMBER
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFnumber() {
        return fnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DETAILCASETYPE.FNUMBER
     *
     * @param fnumber the value for T_COM_DETAILCASETYPE.FNUMBER
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFnumber(String fnumber) {
        this.fnumber = fnumber == null ? null : fnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_DETAILCASETYPE.FINICASETYPE
     *
     * @return the value of T_COM_DETAILCASETYPE.FINICASETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public Long getFinicasetype() {
        return finicasetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_DETAILCASETYPE.FINICASETYPE
     *
     * @param finicasetype the value for T_COM_DETAILCASETYPE.FINICASETYPE
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFinicasetype(Long finicasetype) {
        this.finicasetype = finicasetype;
    }
}