package com.creditease.eas.compliance.bean;
/**
 * 案件初步分类
 * @Inicasetype.java
 * created at 2013-10-16 下午07:19:49 by ygq
 * 
 * @author ygq({@link authorEmail})
 * @version $Revision$</br>
 * update: $Date$
 */
public class Inicasetype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_INICASETYPE.FID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private Long fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_INICASETYPE.FNAME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_INICASETYPE.FNUMBER
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    private String fnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_INICASETYPE.FID
     *
     * @return the value of T_COM_INICASETYPE.FID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public Long getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_INICASETYPE.FID
     *
     * @param fid the value for T_COM_INICASETYPE.FID
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFid(Long fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_INICASETYPE.FNAME
     *
     * @return the value of T_COM_INICASETYPE.FNAME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_INICASETYPE.FNAME
     *
     * @param fname the value for T_COM_INICASETYPE.FNAME
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_INICASETYPE.FNUMBER
     *
     * @return the value of T_COM_INICASETYPE.FNUMBER
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public String getFnumber() {
        return fnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_INICASETYPE.FNUMBER
     *
     * @param fnumber the value for T_COM_INICASETYPE.FNUMBER
     *
     * @mbggenerated Sun Sep 29 19:10:18 CST 2013
     */
    public void setFnumber(String fnumber) {
        this.fnumber = fnumber == null ? null : fnumber.trim();
    }
}