package com.creditease.eas.compliance.bean;
/**
 * 投诉人员中间表
 * @author ygq
 *
 */
public class RelCompersonTemp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_REL_COMPERSON.FID
     *
     * @mbggenerated Tue Oct 22 10:42:49 CST 2013
     */
    private Long fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_REL_COMPERSON.FCOMPID
     *
     * @mbggenerated Tue Oct 22 10:42:49 CST 2013
     */
    private Long fcompid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COM_REL_COMPERSON.FPERSONID
     *
     * @mbggenerated Tue Oct 22 10:42:49 CST 2013
     */
    private Long fpersonid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_REL_COMPERSON.FID
     *
     * @return the value of T_COM_REL_COMPERSON.FID
     *
     * @mbggenerated Tue Oct 22 10:42:49 CST 2013
     */
    public Long getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_REL_COMPERSON.FID
     *
     * @param fid the value for T_COM_REL_COMPERSON.FID
     *
     * @mbggenerated Tue Oct 22 10:42:49 CST 2013
     */
    public void setFid(Long fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_REL_COMPERSON.FCOMPID
     *
     * @return the value of T_COM_REL_COMPERSON.FCOMPID
     *
     * @mbggenerated Tue Oct 22 10:42:49 CST 2013
     */
    public Long getFcompid() {
        return fcompid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_REL_COMPERSON.FCOMPID
     *
     * @param fcompid the value for T_COM_REL_COMPERSON.FCOMPID
     *
     * @mbggenerated Tue Oct 22 10:42:49 CST 2013
     */
    public void setFcompid(Long fcompid) {
        this.fcompid = fcompid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COM_REL_COMPERSON.FPERSONID
     *
     * @return the value of T_COM_REL_COMPERSON.FPERSONID
     *
     * @mbggenerated Tue Oct 22 10:42:49 CST 2013
     */
    public Long getFpersonid() {
        return fpersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COM_REL_COMPERSON.FPERSONID
     *
     * @param fpersonid the value for T_COM_REL_COMPERSON.FPERSONID
     *
     * @mbggenerated Tue Oct 22 10:42:49 CST 2013
     */
    public void setFpersonid(Long fpersonid) {
        this.fpersonid = fpersonid;
    }
}