package com.creditease.eas.institutional.dao;

import java.util.Map;

import org.springframework.stereotype.Repository;

import com.creditease.eas.institutional.bean.LogBaserecordIns;
@Repository
public interface LogBaserecordInsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_BASERECORD_INS
     *
     * @mbggenerated Thu Dec 26 09:35:35 CST 2013
     */
    int insert(LogBaserecordIns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_BASERECORD_INS
     *
     * @mbggenerated Thu Dec 26 09:35:35 CST 2013
     */
    int insertSelective(LogBaserecordIns record);
    /**
     * 获取制度平台数据推送日志中最近成功推送的时间
     * @param paramMap 仅包含推送数据类型
     * @return
     * @throws Exception
     */
    Map<String,Object> selectLastMaxRecordTime(Map paramMap) throws Exception;
}