package com.creditease.eas.hrnew.bean;

import java.util.Date;

public class BaseLogRecordSMP {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_BASERECORD_SMP.ID
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_BASERECORD_SMP.FUNC_NAME
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    private String funcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_BASERECORD_SMP.OPERATETYPE
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    private Long operatetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_BASERECORD_SMP.EXCEPTIONINFO
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    private String exceptioninfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_BASERECORD_SMP.IFSUCCESS
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    private int ifsuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_BASERECORD_SMP.COUNT
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    private int count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_BASERECORD_SMP.RECDATE
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    private Date recdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_BASERECORD_SMP.TYPEID
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    private Long typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_BASERECORD_SMP.EXCEPTCODE
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    private Long exceptcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_BASERECORD_SMP.UPDATEDATE
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_BASERECORD_SMP.EXP1
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    private Object exp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_BASERECORD_SMP.EXP2
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    private Object exp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_BASERECORD_SMP.EXP3
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    private Object exp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_BASERECORD_SMP.EXP4
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    private Object exp4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_BASERECORD_SMP.EXP5
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    private Object exp5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_BASERECORD_SMP.ID
     *
     * @return the value of T_LOG_BASERECORD_SMP.ID
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_BASERECORD_SMP.ID
     *
     * @param id the value for T_LOG_BASERECORD_SMP.ID
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_BASERECORD_SMP.FUNC_NAME
     *
     * @return the value of T_LOG_BASERECORD_SMP.FUNC_NAME
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public String getFuncName() {
        return funcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_BASERECORD_SMP.FUNC_NAME
     *
     * @param funcName the value for T_LOG_BASERECORD_SMP.FUNC_NAME
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public void setFuncName(String funcName) {
        this.funcName = funcName == null ? null : funcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_BASERECORD_SMP.OPERATETYPE
     *
     * @return the value of T_LOG_BASERECORD_SMP.OPERATETYPE
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public Long getOperatetype() {
        return operatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_BASERECORD_SMP.OPERATETYPE
     *
     * @param operatetype the value for T_LOG_BASERECORD_SMP.OPERATETYPE
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public void setOperatetype(Long operatetype) {
        this.operatetype = operatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_BASERECORD_SMP.EXCEPTIONINFO
     *
     * @return the value of T_LOG_BASERECORD_SMP.EXCEPTIONINFO
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public String getExceptioninfo() {
        return exceptioninfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_BASERECORD_SMP.EXCEPTIONINFO
     *
     * @param exceptioninfo the value for T_LOG_BASERECORD_SMP.EXCEPTIONINFO
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public void setExceptioninfo(String exceptioninfo) {
        this.exceptioninfo = exceptioninfo == null ? null : exceptioninfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_BASERECORD_SMP.IFSUCCESS
     *
     * @return the value of T_LOG_BASERECORD_SMP.IFSUCCESS
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public int getIfsuccess() {
        return ifsuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_BASERECORD_SMP.IFSUCCESS
     *
     * @param ifsuccess the value for T_LOG_BASERECORD_SMP.IFSUCCESS
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public void setIfsuccess(int ifsuccess) {
        this.ifsuccess = ifsuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_BASERECORD_SMP.COUNT
     *
     * @return the value of T_LOG_BASERECORD_SMP.COUNT
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public int getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_BASERECORD_SMP.COUNT
     *
     * @param count the value for T_LOG_BASERECORD_SMP.COUNT
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public void setCount(int count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_BASERECORD_SMP.RECDATE
     *
     * @return the value of T_LOG_BASERECORD_SMP.RECDATE
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public Date getRecdate() {
        return recdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_BASERECORD_SMP.RECDATE
     *
     * @param recdate the value for T_LOG_BASERECORD_SMP.RECDATE
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public void setRecdate(Date recdate) {
        this.recdate = recdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_BASERECORD_SMP.TYPEID
     *
     * @return the value of T_LOG_BASERECORD_SMP.TYPEID
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public Long getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_BASERECORD_SMP.TYPEID
     *
     * @param typeid the value for T_LOG_BASERECORD_SMP.TYPEID
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public void setTypeid(Long typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_BASERECORD_SMP.EXCEPTCODE
     *
     * @return the value of T_LOG_BASERECORD_SMP.EXCEPTCODE
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public Long getExceptcode() {
        return exceptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_BASERECORD_SMP.EXCEPTCODE
     *
     * @param exceptcode the value for T_LOG_BASERECORD_SMP.EXCEPTCODE
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public void setExceptcode(Long exceptcode) {
        this.exceptcode = exceptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_BASERECORD_SMP.UPDATEDATE
     *
     * @return the value of T_LOG_BASERECORD_SMP.UPDATEDATE
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_BASERECORD_SMP.UPDATEDATE
     *
     * @param updatedate the value for T_LOG_BASERECORD_SMP.UPDATEDATE
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_BASERECORD_SMP.EXP1
     *
     * @return the value of T_LOG_BASERECORD_SMP.EXP1
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public Object getExp1() {
        return exp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_BASERECORD_SMP.EXP1
     *
     * @param exp1 the value for T_LOG_BASERECORD_SMP.EXP1
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public void setExp1(Object exp1) {
        this.exp1 = exp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_BASERECORD_SMP.EXP2
     *
     * @return the value of T_LOG_BASERECORD_SMP.EXP2
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public Object getExp2() {
        return exp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_BASERECORD_SMP.EXP2
     *
     * @param exp2 the value for T_LOG_BASERECORD_SMP.EXP2
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public void setExp2(Object exp2) {
        this.exp2 = exp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_BASERECORD_SMP.EXP3
     *
     * @return the value of T_LOG_BASERECORD_SMP.EXP3
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public Object getExp3() {
        return exp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_BASERECORD_SMP.EXP3
     *
     * @param exp3 the value for T_LOG_BASERECORD_SMP.EXP3
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public void setExp3(Object exp3) {
        this.exp3 = exp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_BASERECORD_SMP.EXP4
     *
     * @return the value of T_LOG_BASERECORD_SMP.EXP4
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public Object getExp4() {
        return exp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_BASERECORD_SMP.EXP4
     *
     * @param exp4 the value for T_LOG_BASERECORD_SMP.EXP4
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public void setExp4(Object exp4) {
        this.exp4 = exp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_BASERECORD_SMP.EXP5
     *
     * @return the value of T_LOG_BASERECORD_SMP.EXP5
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public Object getExp5() {
        return exp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_BASERECORD_SMP.EXP5
     *
     * @param exp5 the value for T_LOG_BASERECORD_SMP.EXP5
     *
     * @mbggenerated Wed Jul 03 16:06:54 CST 2013
     */
    public void setExp5(Object exp5) {
        this.exp5 = exp5;
    }
}